phoenix-rtos/phoenix-rtos-devices

multi/imxrt-multi/Makefile, multi/imxrt-multi/common.h, multi/imxrt-multi/config.h, multi/imxrt-multi/gpio.c, multi/imxrt-multi/imxrt-multi.c, multi/imxrt-multi/imxrt-multi.h, multi/imxrt-multi/imxrt1060.h, multi/imxrt-multi/spi.c, multi/imxrt-multi/spi.h, multi/imxrt-multi/tests/multi_tests.c, multi/imxrt-multi/tests/spi_tests.c, multi/imxrt-multi/uart.c
imxrt-multi: add spi driver and tests; receive uart's msg on separate port.
=> imxrt-multi: add spi driver and tests; receive uart's msg on separate port.

multi/stm32l4-multi/Makefile, multi/stm32l4-multi/adc.c, multi/stm32l4-multi/common.h, multi/stm32l4-multi/config.h, multi/stm32l4-multi/dma.c, multi/stm32l4-multi/exti.c, multi/stm32l4-multi/flash.h, multi/stm32l4-multi/gpio.c, multi/stm32l4-multi/lib/libuart.c, multi/stm32l4-multi/lib/libuart.h, multi/stm32l4-multi/rcc.c, multi/stm32l4-multi/rcc.h, multi/stm32l4-multi/rtc.c, multi/stm32l4-multi/spi.c, multi/stm32l4-multi/stm32-multi.h, multi/stm32l4-multi/uart.c
WIP: In the next step I will move SPI driver to lib. **Please don't merge yet**, if this passes code review I will add SPI before merging.
=> stm32l4-multi: Moved uart to multilib

adc/ad7779/ad7779-driver.c, adc/ad7779/ad7779.c, adc/ad7779/ad7779.h, adc/ad7779/adc-api.h
Added device error status check, hardware reset,
unused channels disabling. Fixed memory deallocation
when initialization is unsuccessful.
=> imxrt/ad7779: add new capabilities to device api

multi/imxrt-multi/uart.c
The reason for the change is that with 230k and 460k and sending long frames I continuously observed numerous system freezes, after changing to the algorithm proposed the problem disappeared.
I've changed the UART baud rate calculation to an idea taken from the SDK. Please take a look at the attached comparison table below. I've checked the algorithm on hardware with ~500 octet long frames (the most common baud rates I use are 230400 and 460800).
Additionally, I added a line that disables TX and RX interrupts like in imx6ull (sticky conds), out of the condWait loop.
https://github.com/phoenix-rtos/phoenix-rtos-devices/blob/05008b584058340204413cba3ef27a4fe55a5d0c/tty/imx6ull-uart/imx6ull-uart.c#L161-L168
Maybe this will help to stop receiving FE and Noisy interrupts (RX), even if they are …
=> imxrt-multi: UART baudrate calculation based on sdk

multi/imxrt-multi/Makefile, multi/imxrt-multi/common.h, multi/imxrt-multi/config.h, multi/imxrt-multi/imxrt-multi.c, multi/imxrt-multi/imxrt-multi.h, multi/imxrt-multi/imxrt1060.h, multi/imxrt-multi/imxrt1170.h, multi/imxrt-multi/uart.c
Just allowing CI to perform checks.
=> imxrt-multi: imxrt117x uart driver

multi/imxrt-multi/uart.c
During debugging with jtag, when the processor is halted and receiving data with UART (e.g. keyboard typing on the console serial port)  - writing to the hardware FIFO (more characters than the FIFO size) causes the UART to overrun and locks it (until the  FIFO register is flushed and status flag is cleared by W1C), so no more data can be received after the processor is resumed - the attached commit resolves this problem, additionally adds clear status flags for noisy and framing errors.
A similar change is also added to the plo (separate PR):
https://github.com/phoenix-rtos/plo/pull/28
=> imxrt-multi: add uart rx overrun, noisy and framing error handling

multi/imxrt-multi/uart.c
The same applies to plo: https://github.com/phoenix-rtos/plo/pull/32
=> imxrt-multi: Rewrite of uart RX status flags handling

adc/ad7779/ad7779-driver.c
=> ad7779: fix edma buffer initialization after reset

adc/ad7779/ad7779-driver.c, adc/ad7779/ad7779.c
=> ad7779: fix log types and levels

adc/ad7779/Makefile, display/oled-128O064B0/Makefile
=> periphs: remove '-driver' suffix from peripherals

multi/imxrt-multi/Makefile, multi/imxrt-multi/config.h, multi/imxrt-multi/imxrt-multi.c, multi/imxrt-multi/imxrt-multi.h, multi/imxrt-multi/imxrt1170.h, multi/imxrt-multi/spi.c
=> imxrt117x/imxrt-multi: port and enable spi

Makefile, storage/imx6ull-flash/flashsrv.c
=> makes: install binaries into rootfs by make rules

adc/ade7913/Makefile, adc/ade7913/ade7913-test.c, adc/ade7913/ade7913.c, adc/ade7913/ade7913.h
=> ade7913: add API and test for ADE7913 device

display/virtio-gpu/virtio-gpu.c, storage/virtio-blk/virtio-blk.c
PR in phoenix-rtos-corelibs has to be merged first: [link](https://github.com/phoenix-rtos/phoenix-rtos-corelibs/pull/4)
=> Adapt renamed library headers + clang-format compliance JIRA: RTOS-22

storage/imxrt-flash/flashsrv.c
Change meterfs thread stack size
After change of place where data structure is built in meterfs, there is need of bigger stack.
=> flashsrv: bigger meterfs stack size

adc/ade7913/Makefile, adc/ade7913/adc-api.h, adc/ade7913/ade7913-driver.c, adc/ade7913/ade7913-test.c, adc/ade7913/ade7913.c, adc/ade7913/ade7913.h, adc/ade7913/gpio.c, adc/ade7913/gpio.h, dma/imxrt-edma/edma.h, dma/imxrt-edma/imxrt-edma.c
Changing edma api so that it could be used for ade7913-driver. Adding configurable ade7913-driver
for control over multiple ade7913 adcs. 
Adding new functionality required for devices.
=> imxrt: add ade7913-driver 

multi/stm32l1-multi/uart.c, multi/stm32l4-multi/libmulti/libuart.h
JIRA: ISC-123
Volatile is needed as values is changed in interrupt handler
It's for hardening. Found while analysing unconnected issue.
=> stm32lX-multi: Add missing volatile

storage/imx6ull-flash/imx6ull-flash-test.c
Added test_bootrom() which destroys (either by breaking ECC or by setting BBM) structures used by the BootROM. Allows to verify BootROM behaviour.
[JIRA: DTR-95](https://jira.phoenix-rtos.com/browse/DTR-95)
=> imx6ull-flash-test: add BootROM test

storage/imx6ull-flash/imx6ull-flash-test.c
Added flash ECC tests (meta and data chunks are checked for correcting maximum recoverable number of bit flips).
Added read disturb stress test.
[JIRA: DTR-96](https://jira.phoenix-rtos.com/browse/DTR-96)
=> imx6ull-flash-test: add ECC tests

watchdog/imx6ull/imx6ull-wdg.c
Small fixes for watchdog:
- support mtWrite correctly (return all bytes written correctly)
- suspend in debug mode
- don't try to disable watchdog (impossible if enabled anyway)
- kick watchdog after setting new timeout (otherwise old timeout will still be in effect)
JIRA: DTR-122
=> imx6ull-wdg: small fixes

Makefile, _targets/Makefile.armv7a7-imx6ull, i2c/common/Makefile, i2c/common/i2c-msg.h, i2c/common/i2c.h, i2c/common/libi2c-msg.c, i2c/imx6ull/Makefile, i2c/imx6ull/imx6ull-i2c.c, i2c/imx6ull/libimx6ull-i2c.c, rtc/Makefile, rtc/pcf85363a.c, rtc/rtc.h, sensor/Makefile, sensor/temp-nct75.c
Add `i2c` master common API, add `imx6ull` implementation, and implement drivers for 2 i2c devices. Current setup supports using `i2c` bus either as a library (embedded directly int i2c device driver) or as a separate program with message communication (needed if more than one slave device is placed on the same i2c bus). Both approaches were tested on `imx6ull` target with success.
Commit summary:
- i2c: add generic interface and message implementation …
- i2c: add imx6ull bus driver
- rtc: add pcf85363a i2c rtc support
- sensor: add nct75 i2c temperature sensor support …
Needed for DTR project, relevant JIRA tickets in respective commit messages.
=> `i2c` common API: add i2c imx6ull BUS driver and some simple i2c slave device drivers

_targets/Makefile.armv7a9-zynq7000, tty/zynq7000-uart/Makefile, tty/zynq7000-uart/zynq7000-uart.c
Add driver implementation for uart on Zynq-7000:
- console number and baudrate is set via args,
- each uart is initialized.
JIRA: PD-191
Needed for run user space apps on new target armv7a9-zynq7000
=> tty/zynq7000-uart: add uart's driver

multi/imxrt-multi/trng.c, multi/imxrt-multi/uart.c, multi/stm32l4-multi/tty.c, storage/imx6ull-flash/flashsrv.c, storage/pc-ata/atasrv.c, storage/virtio-blk/virtio-blk.c, tty/imx6ull-uart/imx6ull-uart.c, tty/pc-tty/ttypc.c, tty/spike-tty/spike-tty.c, tty/uart16550/uart16550.c, tty/uart16550/uarthw-pc.c, tty/uart16550/uarthw-riscv.c, tty/zynq7000-uart/zynq7000-uart.c
Changes required for LFS (Large Files Support):
- storage device drivers return `off_t` cast to `long long` as a partition size (`attr` parameter),
- check `msg.o.attr.err` for errors after sending `mtGetAttr`/`mtSetAttr` messages,
- major `spike-tty` and `uart16550` code clean up,
[JIRA: DTR-103](https://jira.phoenix-rtos.com/browse/DTR-103)
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/240
https://github.com/phoenix-rtos/libphoenix/pull/133
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/46
https://github.com/phoenix-rtos/phoenix-rtos-lwip/pull/43
https://github.com/phoenix-rtos/phoenix-rtos-posixsrv/pull/8
https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/56
https://github.com/phoenix-rtos/phoenix-rtos-usb/pull/13 …
=> Adapt to Large Files Support changes

tty/zynq7000-uart/zynq7000-uart.c
On hardware it was allowed to clear status register in interrupt handler but testing the same code under emulator doesn't work. It occurred that status register can be cleared only if TX fifo is empty. 
For this reason, interrupt is disabled in handler and enabled again after clearing fifo.
JIRA: PD-203
RX Trigger IRQ appears always when RX fifo contains a byte above threshold. So that this interrupt is generated almost all the time when something is in fifo. On hardware it was invisible, but emulator has stared hanging.
=> zynq7000-uart: disable RX Trigger IRQ after receiving one

_targets/Makefile.armv7a7-imx6ull, _targets/Makefile.armv7m7-imxrt106x, usb/cdc-demo/Makefile, usb/cdc-demo/cdc-demo.c, usb/libusbclient/imxrt-usbc/phy.c
JIRA: RTOS-116
`cdc-demo` has been removed during phoenix-rtos-usb refactorization. Let's move it to phoenix-rtos-devices.
- [] My changes generate no new compilation warnings for any of the targets.
=> usb: Add cdc-demo app

adc/ad7779/Makefile
=> ad7779: fix buffers' size and count

spi/imx6ull-ecspi/libecspi.c
=> imx6ull: ecspi: change default pins for ecspi1

adc/ad7779/ad7779-driver.c, gpio/imx6ull-gpio/imx6ull-gpio.c
Additionally fix log in ad7779
=> imx6ull: gpio: add priority argument

storage/imx6ull-flash/flashsrv.c
- rewrite options parsing
- parse/validate options first, then create necessary partitions
- common logging
- introduce partition names with symlink creation
- select rootfs to be mounted based on SRC secondary boot 
JIRA: DTR-181
Needed for FW upgrade (the same kernel image for primary/secondary boot, current rootfs detection, etc.)
=> imx6ull-flash: rewrite initialization 

multi/stm32l4-multi/flash.c
Added bank remaping detection for page erase
JIRA: ISC-150
Fixes STM32L4 flash erase/write
=> stm32l4-multi/flash: Fixed operr being uninitialized.

libklog/Makefile, libklog/libklog.c, libklog/libklog.h, tty/imx6ull-uart/Makefile, tty/imx6ull-uart/imx6ull-uart.c
=> Add libklog

tty/imx6ull-uart/imx6ull-uart.c
=> imx6ull-uart: Fix clang format warning

otp/imx6ull-otp/imx6ull-otp.c
=> imx6ull-otp: Change serial number format

_targets/Makefile.armv7a9-zynq7000, storage/zynq7000-flash/Makefile, storage/zynq7000-flash/flashcfg.c, storage/zynq7000-flash/flashcfg.h, storage/zynq7000-flash/flashdrv.c, storage/zynq7000-flash/flashdrv.h, storage/zynq7000-flash/qspi.c, storage/zynq7000-flash/qspi.h, storage/zynq7000-flash/tests/Makefile, storage/zynq7000-flash/tests/flashdrv.c, storage/zynq7000-flash/tests/test.yaml
The following PR consists of:
- qspi driver,
- nor flash memory driver,
- cfi interface,
- functional test for nor flash memory.
=> zynq7000-flash: add driver for nor flash memory and functional tests

storage/zynq7000-flash/flashdrv.c
=> zynq7000-flash/flashdrv.c: fixed error value checking

usb/ehci/ehci.c
JIRA: DTR-227
This change fixes a bug, which caused an EHCI host controller to fail to detect a device connection, if it had been connected before the system started.
This change is required to use USB stack on imx6ull platform.
=> usb/ehci: Set interrupt handler before enabling interrupts

multi/stm32l4-multi/flash.c, multi/stm32l4-multi/flash.h, multi/stm32l4-multi/stm32l4-multi.c, multi/stm32l4-multi/stm32l4-multi.h
JIRA: SKAL-258
This change introduces dual booting to STM32L4 targets. The new message (flash_switch) toggles a dual boot flag and causes a write to flash option bytes. The device is then reset by flash option loader (OBL_LAUNCH) - a normal reset does not apply the changes during boot.
The reset itself could be moved to the kernel (pctl_reboot) but it still needs flash-related code (unlocking the flash registers).
=> stm32l4-multi/flash: Add bank switching (dual boot)

storage/imx6ull-flashnor/Makefile, storage/imx6ull-flashnor/flashnor-ecspi.c, storage/imx6ull-flashnor/flashnor-ecspi.h, storage/imx6ull-flashnor/flashnor-test.c
Add basic test of read/write/erase every sixteenth block of nor flash.
=> imx6ull: add basic tests for flashnor

storage/umass/umass.c, tty/usbacm/usbacm.c, usb/ehci/ehci-hub.c, usb/ehci/ehci.c, usb/ehci/ehci.h
The aim of this PR is to make usb stack more stable and to make it handle more potential errors.
=> Make USB stack more robust

i2c/imx6ull/imx6ull-i2c.c, rtc/pcf85363a.c, sensor/temp-nct75.c
=> imx6ull: print successful driver initialization

storage/imx6ull-flash/imx6ull-flash-test.c
Change default test in nand-flash test, also change output formatting.
=> imx6ull: change flash test to erase/write/read

multi/stm32l4-multi/gpio.c
=> stm32l4-multi/gpio: Added memory bariers, rearanged gpio_config

storage/imx6ull-flash/imx6ull-flash-test.c
Add write/read/erase with error checking
=> imx6ull-flash: add read/write/erase test with ecc

tty/pc-tty/ttypc_vt.c
Fixed last character in a row flag being canceled by not printable character(s).
Fixes phoenix-rtos/phoenix-rtos-project#354
[JIRA: RTOS-169](https://jira.phoenix-rtos.com/browse/RTOS-169)
=> pc-tty: fix last character in a row flag being canceled by ANSI escape code

storage/imx6ull-flashnor/flashnor-ecspi.c
=> imx6ull: nor: add Adesto AT25SF321A chip jedec

storage/zynq7000-flash/qspi.c
- add mutex for qspi transaction for multithreaded access
- add brackets for conditional statements to be consistent with MISRA
PD-216
=> zynq7000/qspi: add mutex lock/unlock in qpsi start and stop

storage/imx6ull-flash/README.md, storage/imx6ull-flash/flashdrv.c, storage/imx6ull-flash/flashsrv.c, storage/imx6ull-flash/imx6ull-flash-test.c, storage/imx6ull-flash/imx6ull-flashdrv.h
This reverts commit e4ccfa4461d02f67f7d5f56152b57ecc8c116b6c.
This reverts commit 282739164fdcc57cfec39680108176e0032fe6b9.
This reverts commit f42147f64a641ff623acaa4780a011204229f287.
JIRA: DTR-303
=> Revert faster NAND improvements

tty/usbacm/usbacm.c, usb/ehci/ehci-hub.c, usb/ehci/ehci.c, usb/ehci/ehci.h
This change make a usbacm driver use the new asynchronous API introduced by: https://github.com/phoenix-rtos/phoenix-rtos-usb/pull/22.
This change allows increasing usbacm bandwidth from initial 500 kB/s to 33 000 kB/s. However to achieve such a bandiwidth, one should increase number of urbs by setting `USBACM_N_URBS` to at least 8. A default value of 2 allows 3000 kB/s.
=> usbacm: Use asynchronous transfers

tty/libtty/libtty.c
=> libtty: libtty_getchar() fix

adc/ad7779/ad7779-driver.c
Add the ability to change the priority of the main driver thread.
=> ad7779: add priority argument

storage/zynq7000-flash/flashdrv.c
Associated with changes in phoenix-rtos-corelibs.
PD-216
=> storage/zynq-7000: update storage_mtd_t structure

storage/imxrt-flash/flashsrv.c
=> storage/imxrt-flash: Allow open/close operations for raw partitions

storage/imx6ull-flash/flashsrv.c
The majority of the code has been rewritten. The user interface to the server is the same.
**NOTE for reviewers:**
- in the previous implementation the failure of a `create_dev` function has been treated as a non-critical error. Should be the same here? In the code, there is a note in the `TODO` comment.
- `flashsrv_write` had a special feature - erasing memory if `data` is passed as a `NULL`. Is it a feature or a bug? In my opinion it is a bug.
DTR-102
=> storage/imx6ull-flashsrv: a new version uses libstorage library and flashdev module

storage/zynq7000-flash/flashdrv.c, storage/zynq7000-flash/tests/flashdrv.c, storage/zynq7000-flash/zynq7000-flash.c
- update tests,
- check input arguments in flashsrv,
- move erase block from blkWrite to sync function
PD-216
=> zynq7000-flash: cleaning up code: fixing minor vulnerabilities

storage/zynq7000-flash/flashdrv.c
=> stroage/zynq-7000: apply changes in MTD interface

storage/imx6ull-flashnor/flashnor-ecspi.c, storage/imx6ull-flashnor/flashnor-ecspi.h, storage/imx6ull-flashnor/flashnor.c, storage/imxrt-flash/flashsrv.c, storage/zynq7000-flash/flashdrv.c, storage/zynq7000-flash/zynq7000-flash.c, tty/imx6ull-uart/imx6ull-uart.c, tty/imx6ull-uart/lf_fifo.h, tty/libtty/libtty.c, tty/libtty/libtty.h, tty/pc-tty/ttypc_vt.c, tty/spike-tty/spike-tty.c, tty/zynq7000-uart/zynq7000-uart.c
- merge master into feature/mtd
- apply changes from MTD interface to flash server
=> merge master into feature/mtd

storage/imx6ull-flash/flashdev.c, storage/imx6ull-flash/flashsrv.c
=> storage/imx6ull: appply new MTD interface to flashsrv and flashdev

storage/imx6ull-flash/flashdrv.c
Fixed DMA irq handler (wrong status register was checked before). Added DMA error checks.
[JIRA: DTR-320](https://jira.phoenix-rtos.com/browse/DTR-320)
=> imx6ull-flash: fix DMA irq handler, add error checks

storage/imx6ull-flash/flashdev.c
Fixed ECC checks.
[JIRA: DTR-102](https://jira.phoenix-rtos.com/browse/DTR-102)
=> imx6ull-flash: fix read with ECC checks

multi/imxrt-multi/imxrt-multi.c, multi/imxrt-multi/trng.c
=> imxrt-multi: Added /dev/random. Allow byte access to TRNG

tty/imx6ull-uart/imx6ull-uart.c
Edge triggered interrupts can block forever if interrupt
arrives inside interrupt handler. Avoid this situation by
disabling error interrupts and moving TX to interrupt thread.
Detect potential RX interrupt inside interrupt handler and fix
it by disabling/enabling RX interrupt (forced trigger).
JIRA: DTR-283
=> uart-imx6ull: interrupt blocking fix

_targets/Makefile.armv7a9-zynq7000, gpio/zynq7000-pwm/Makefile, gpio/zynq7000-pwm/README.md, gpio/zynq7000-pwm/ip/README.md, gpio/zynq7000-pwm/ip/pwm8x.v, gpio/zynq7000-pwm/ip/pwm8x_S00_AXI.v, gpio/zynq7000-pwm/pwm.c
=> Added zynq7000-pwm driver and IP core

_targets/Makefile.armv7a9-zynq7000, storage/imx6ull-flash/Makefile, storage/imx6ull-flash/flashdev.c, storage/imx6ull-flash/flashdrv.c, storage/imx6ull-flash/flashsrv.c, storage/imx6ull-flash/imx6ull-flashdev.h, storage/imx6ull-flash/imx6ull-flashdrv.h, storage/zynq7000-flash/Makefile, storage/zynq7000-flash/flashdrv.c, storage/zynq7000-flash/tests/flashdrv.c, storage/zynq7000-flash/zynq7000-flash.c
The `feature/mtd` branch is rebased to master branch and renamed to `HBuczynski/mtd` to avoid mess in the commit history.
=> feature/mtd: merge into master

storage/zynq7000-flash/flashcfg.c
Adding new flash memory device.
PP-34
=> storage/zynq-7000: add Winbond W25Q128JV NOR flash memory

tty/zynq7000-uart/zynq7000-uart.c
UART number is taken from args. 
Current implementation sets the same baudrate for all uarts.
In the new approach, each uart instance is in a separate process.
=> zynq7000-uart: launch uart instance as a separate process

_targets/Makefile.armv7a9-zynq7000, gpio/zynq7000-xgpio/Makefile, gpio/zynq7000-xgpio/README.md, gpio/zynq7000-xgpio/xgpio.c
JIRA: PP-37
Driver for AXI GPIO Xilinx IP
=> Added zynq7000-xgpio driver

tty/usbacm/usbacm.c
JIRA: DTR-324
This changes the behaviour of a blocking read. From now the reader should be blocked until all the data is read or an error happens. What's more the number of threads communicating with the USB host stack is reduced to one, in order to minimize the resources usage and ensure that urbs statuses are handled in an exact FIFO order.
Those changes are needed in order to optimize read overhead by minimizing number of exchanged messages.
- [] All new and existing linter checks and tests passed.
=> tty/usbacm: Block a reader, until all the data is read

sensors/sensors.c
=> sensors/sensors.c: fix checking NULL value

_targets/Makefile.armv7a9-zynq7000, spi/common/Makefile, spi/common/libspi-msg.c, spi/common/spi-msg.h, spi/common/spi.h, spi/zynq7000-spi/Makefile, spi/zynq7000-spi/libzynq7000-spi.c, spi/zynq7000-spi/zynq7000-spi.c
SPI library and server implementation for zynq7000.
Usage example (PmodNAV accelerometer communication):
```c
#include <spi.h>
#include <spi-msg.h>
#include <stdio.h>
#include <string.h>
int main(void)
{
spimsg_ctx_t ctx = { .mode = SPI_MODE3, .speed = 6250000 };
unsigned char cmd = (1 << 7) | 0xf; /* Read WHO AM I register */
unsigned char val;
int err;
/* Get SPI1 SS0 oid */
err = spimsg_open(1, 0, &ctx);
if (err < 0) {
printf("acc: failed to open SPI message context, err: %s\n", strerror(err));
return 1;
}
err = spimsg_xfer(&ctx, &cmd, sizeof(cmd), &val, sizeof(val), sizeof(cmd));
if (err < 0) {
printf("acc: failed to perform SPI transaction, err: %s\n", strerror(err));
return 1;
}
printf("acc: WHO AM I returned %#x\n", val);
err = spimsg_close(&ctx);
if (err < 0) {
printf("acc: failed …
```
=> zynq7000-spi: initial implementation

sensors/Makefile, sensors/gps/nmea.h
- sensors: gps: does not export nmea.h
Exporting `nmea.h` for a few useful enums is not necessary.
JIRA: PP-36
=> sensors: gps: does not export nmea.h

sensors/imu/lsm9dsxx.c
JIRA: PP-6
add WHOAMI register check before continuing with hardware setup. Also fixed code issue with pointer type assigned to `spiCtx`.
=> sensors:lsm9dsxx_imu: add whoami recognition

sensors/Makefile, sensors/mag/lsm9dsxx.c
JIRA: PP-6
lsm9dsxx magnetometer driver code to sensorhub
Due to hardware issues this was not tested on target, thus only draft PR is issued.
=> sensors: add lsm9dsxx magnetometer driver

sensors/baro/lps25xx.c
JIRA: PP-6
Adding lsp25xx barometer driver to sensor manager.
Due to hardware issues this was not tested on the target, thus only draft PR is issued.
=> sensors:baro: add lsp25xx barometer driver

gpio/zynq7000-xgpio/README.md, gpio/zynq7000-xgpio/xgpio.c
=> xpgio: Improve interface - negate dir, so 0 means input, 1 output

_targets/Makefile.armv7a9-zynq7000, gpio/zynq7000-gpio/Makefile, gpio/zynq7000-gpio/gpio.c, gpio/zynq7000-gpio/gpio.h, gpio/zynq7000-gpio/gpiosrv.c, gpio/zynq7000-gpio/libzynq7000-gpio-msg.c, gpio/zynq7000-gpio/zynq7000-gpio-msg.h
Added GPIO driver and server implementation.
[JIRA: PP-46](https://jira.phoenix-rtos.com/browse/PP-46)
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/437
=> zynq7000-gpio: add driver implementation

gpio/zynq7000-gpio/zynq7000-gpio-msg.h
Fixed typos.
[JIRA: PP-46](https://jira.phoenix-rtos.com/browse/PP-46)
=> zynq7000-gpio: fix typos

spi/common/libspi-msg.c, spi/common/spi.h, spi/zynq7000-spi/libzynq7000-spi.c, spi/zynq7000-spi/zynq7000-spi.c
Allow for external SS control.
Changed SPI registers from enums to defines for MISRA conformance.
[JIRA: PP-44](https://jira.phoenix-rtos.com/browse/PP-44)
=> zynq7000-spi: add support for external SS line control

sensors/baro/lps25xx.c, sensors/imu/lsm9dsxx.c, sensors/mag/lsm9dsxx.c
Changes:
1. `err` variable type from unsigned to signed
2. logical OR instead bitwise OR
=> sensors: fix whoamiCheck() function

sensors/mag/lsm9dsxx.c
JIRA: PD-43
Correction of conversion parameters for lsm9dsxx magnetometer to match output value unit with the one of sensorhub
=> sensors: lsm9dsxx mag convesion fix

sensors/Makefile, sensors/baro/lps25xx.c, sensors/imu/lsm9dsxx.c, sensors/libsensors-spi.c, sensors/mag/lsm9dsxx.c, sensors/sensors-spi.h, sensors/sensors.c
Added interface for SPI sensors communication.
[JIRA: PP-44](https://jira.phoenix-rtos.com/browse/PP-44)
=> sensors: add library for SPI sensors communication

tty/zynq7000-uart/zynq7000-uart.c
- align thread stacks,
- disable and reset TX and RX before setting baudrate (see Zynq7000 TRM),
- add support for setting no parity,
- enable pull-up and disable HSTL receiver for UART pins configuration (see Zynq7000 TRM),
- allow for setting UART raw mode,
- improved code formatting,
[JIRA: PP-41](https://jira.phoenix-rtos.com/browse/PP-41)
=> zynq7000-uart: driver fixes necessary for GPS module communication

tty/usbacm/usbacm.c
Fix deadlock scenario.
JIRA: BES-225
=> tty/usbacm: Set number of umsg threads with a define

storage/zynq7000-flash/qspi.c
more details:
- confugure feedback clock pin,
- feedback clock has to be set if the frequency > 40 MHz, otherwise the controller does not work as expected
PD-278
=> storage/zynq7000/qspi: increase clock freq to 100 MHz

storage/zynq7000-flash/qspi.c
=> storage/zynq7000/qspi: configure qspi pins based on board_config data

multi/stm32l4-multi/flash.c, multi/stm32l4-multi/stm32l4-multi.c, multi/stm32l4-multi/stm32l4-multi.h
JIRA: ISC-191
Remove bank switching from stm32l4-multi - this feature has been moved to plo
This feature stopped working after changes in plo that introduced bank switching in plo
=> stm32l4-multi: Remove bank switch feature (moved to plo)

multi/imxrt-multi/uart.c
JIRA: NIL-287
A fix to appending parity bit to UART data frames for i.MX RT MCUs.
UART configuration for i.MX RT MCUs is different then, for example, for i.MX 6ULL. Parity bit is treated as a part of data bits. So in order to append parity bit to data frame, data length must be incremented.
=> imxrt-multi: uart parity bit appending fix

multi/stm32l4-multi/libmulti/include/libmulti/libhash.h, multi/stm32l4-multi/libmulti/libhash.c
JIRA: SKAL-568
HASH peripheral driver. Only lib version provided, not included in multidrv.
=> stm32l4-multi: Add HASH lib

multi/stm32l4-multi/flash.c, multi/stm32l4-multi/flash.h, multi/stm32l4-multi/stm32l4-multi.c, multi/stm32l4-multi/stm32l4-multi.h
=> stm32l4-multi: add writing and reading otp memory

multi/imxrt-multi/uart.c
JIRA: NIL-287
A fix to reading 7-bit data frames while parity bit is enabled for i.MX RT MCUs.
For i.MX RT MCUs parity bit is treated as a part of data bits. Data register is 8-bit long. So in 7-bit mode with parity enabled last bit is a parity bit.
In 7-bit mode 0x7F mask must be applied.
=> imxrt-multi: uart 7-bit characters read fix

_targets/Makefile.armv7a7-imx6ull, sdio/common/Makefile, sdio/common/sdio.h, sdio/imx6ull/Makefile, sdio/imx6ull/imx6ull-sdio.c
JIRA: RTOS-212
A statically linked SDIO driver library, adapted from lwIP's WHD driver HAL layer.
The goal of this feature is to provide a unified SDIO access interface on applicable platforms. This version has been extracted from already implemented WHD HAL layer, and preliminarily modified to allow for generic functionality.
=> libsdio: unified SDIO driver

storage/imx6ull-flash/flashsrv.c
At this moment we wrongly compare (offs + size) (including parity bits)
with strg->size (without parity bits), causing operations on last blocks
to fail.
Compute raw partition size and compare it with (offs + size).
JIRA: DTR-333
=> imx6ull-flash/flashsrv: Fix raw read/write

sensors/baro/lps25xx.c
JIRA: PP-69
lps25hb driver had an issue of pressure sensor stuck in init mode. Added memory reboot in the beggining of sensor init and delay much greater than datasheet spec memory reboot time (which is below 3ms in datasheet)
=> sensors: add memory reboot to lps25xx init

_targets/Makefile.armv7a9-zynq7000, tty/uart16550/Makefile, tty/uart16550/uart16550.c, tty/uart16550/uarthw-pc.c, tty/uart16550/uarthw-riscv.c, tty/uart16550/uarthw-zynq7000.c, tty/uart16550/uarthw.h
=> UART16550: Add zynq7000 implementation

gpio/zynq7000-pwm/pwm.c
=> zynq7000-pwm: handle mtGetAttr

_targets/Makefile.armv7a9-zynq7000, spi/zynq7000-xspi/Makefile, spi/zynq7000-xspi/libzynq7000-xspi.c, spi/zynq7000-xspi/libzynq7000-xspi.h, spi/zynq7000-xspi/zynq7000-xspi.c
JIRA: PP-85
Add AXI SPI PL driver for zynq7000
=> Add zynq7000-xspi AXI PL IP driver

multi/stm32l4-multi/stm32l4-multi.c
JIRA: ISC-118
Include accidentally removed in https://github.com/phoenix-rtos/phoenix-rtos-devices/commit/65ce7d4bd581a91aa35493ac1bfad9838f06c49e
=> stm32l4-multi: Add missing include

Makefile
=> make: fix Makefile search command

storage/zynq7000-flash/Makefile, storage/zynq7000-flash/flashcfg.c, storage/zynq7000-flash/flashdrv.c, storage/zynq7000-flash/flashdrv.h, storage/zynq7000-flash/tests/Makefile, storage/zynq7000-flash/tests/flashdrv.c
=> Use libcache on zynq7000-flash

multi/stm32l4-multi/rtc.c, multi/stm32l4-multi/rtc.h, multi/stm32l4-multi/stm32l4-multi.c, multi/stm32l4-multi/stm32l4-multi.h
=> stm32l4-multi: Add RTC backup storage implementation

adc/ad7779/Makefile
=> ad7779: Shrink DMA buffers for imxrt target

multi/stm32l4-multi/flash.c, multi/stm32l4-multi/flash.h, multi/stm32l4-multi/stm32l4-multi.c, multi/stm32l4-multi/stm32l4-multi.h
JIRA: ISC-194
Please note that only 8 byte aligned and 8 byte quants write are allowed. STM32L4 flash memory features ECC, so rewrites of these 8 byte quants are not possible - page needs to be erased for these data to be modified.
=> stm32l4-multi: Add program flash raw write and erase to API

sensors/baro/lps25xx.c, sensors/imu/lsm9dsxx.c
HW filtering on data from gyroscope and barometer is not as necessary as on accelerometer so it can be tuned down.
=> sensors: lower HW filtering on baro & gyro

storage/imx6ull-flash/flashdev.c
This behavior is expected by the jffs2. It ignores EBADMSG, if we return a requested number of bytes.
JIRA: DTR-347
=> storage/imx6ull-flash: Continue reading, when EBADMSG occurs

sensors/baro/lps25xx.c
JIRA: PP-107
- Setting pressure and temperature oversampling to the highest possible value after datasheet misunderstanding.
- Correcting temperature oversampling macros names to match their real meaning 
There was a misunderstanding of datasheet which lead to setting the lowest oversampling rate both for temperature and pressure readings of lps25hb. Now they are at the lowest noise settings for both.
=> lps25hb: lowest noise settings

storage/imx6ull-flashnor/storage.c, usb/libusbclient/imx-usbc/client.c
Make devices compatible with fixed threadJoin
- JIRA: RTOS-226
=> devices: fix threadJoin call

tty/uart16550/uart16550.c
The server didn't wait on root. For this reason files have not been registered in `/dev` directory.
PP-117
=> uart16550: fix files registration in dev directory

multi/imxrt-multi/Makefile, multi/imxrt-multi/imxrt-multi.c, multi/imxrt-multi/uart.c, multi/imxrt-multi/uart.h, tty/imx6ull-uart/imx6ull-uart.c, tty/pc-tty/Makefile, tty/pc-tty/ttypc.c, tty/spike-tty/Makefile, tty/spike-tty/spike-tty.c, tty/uart16550/Makefile, tty/uart16550/uart16550.c, tty/zynq7000-uart/Makefile, tty/zynq7000-uart/zynq7000-uart.c
=> add klog to all architecture

_targets/Makefile.armv7a9-zynq7000, i2c/zynq-7000/Makefile, i2c/zynq-7000/libzynq7000-i2c.c, i2c/zynq-7000/zynq7000-i2c.c
=> i2c/zynq7000: add i2c driver

multi/stm32l4-multi/libmulti/libi2c.c
=> stm32l4-multi/i2c: Fix libi2c_stop not being called on error paths

storage/imxrt-flash/nor.c
JIRA: NIL-381
https://github.com/phoenix-rtos/plo/pull/228
=> imxrt-flash: Add W25Q256JVEIQ nor flash

multi/imxrt-multi/uart.c, tty/libtty/libtty.c
=> imxrt-multi: make UART FIFO size configurable in board_config.h

_targets/Makefile.armv7a9-zynq7000, gpio/zynq7000-pwm/Makefile, gpio/zynq7000-pwm/pwm.c, gpio/zynq7000-pwm/zynq7000-pwm-msg.c, gpio/zynq7000-pwm/zynq7000-pwm-msg.h, gpio/zynq7000-pwm/zynq7000-pwm-priv.h
=> zynq7000-pwm: Add binary interface

gpio/zynq7000-pwm/pwm.c
=> zynq7000-pwm: Fix loop end condition

watchdog/imx6ull/imx6ull-wdg.c
Added `-p priority` option for running driver with selected priority.
[JIRA: DTR-386](https://jira.phoenix-rtos.com/browse/DTR-386)
=> imx6ull-wdg: add option for selecting driver priority

libklog/libklog.c
=> libklog: Fix bad errno check

storage/imx6ull-flash/flashdrv.c, storage/imx6ull-flash/flashsrv.c
=> imx6ull-flash fixes

storage/host-flash/host-flash.c, storage/host-flash/host-flash.h, storage/host-flash/host-flashsrv.c, storage/host-flash/host-flashsrv.h, storage/imxrt-flash/flashsrv.c
JIRA: RTOS-419
Adapts host and imxrt flash servers to new meterfs api.
Meterfs had to change to accomodate libstorage.
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/88
=> meterfs: adapt host and imxrt servers

spi/imx6ull-qspi/Makefile, spi/imx6ull-qspi/qspi.c, spi/imx6ull-qspi/qspi.h, storage/imx6ull-flashnor/Makefile, storage/imx6ull-flashnor/flashnor-qspi.c, storage/imx6ull-flashnor/flashnor-qspi.h, storage/imx6ull-flashnor/flashnor-test.c, storage/imx6ull-flashnor/flashnor.c, storage/imx6ull-flashnor/nor/nor.c, storage/imx6ull-flashnor/nor/nor.h
JIRA: RTOS-320
Almost a copy of nor flash driver from plo.
imx6ull: implement nor storage over qspi
This driver is neeted to allow jffs2 rootfs on this target.
=> imx6ull: implement nor storage over qspi

sensors/include/libsensors.h, sensors/simsensor_common/event_queue.c, sensors/simsensor_common/event_queue.h, sensors/simsensor_common/simsensor_reader.c, sensors/simsensor_common/simsensor_reader.h
This PR contains parser for test files prepared for a future tests, which uses sensors. Topic was discussed there: https://github.com/phoenix-rtos/phoenix-rtos-project/discussions/626
Easier testing.
=> simsensor reader: add queue and file reader for sensor event

tty/usbacm/usbacm.c
=> tty/usbacm: fix deadlock on device removal

multi/imxrt-multi/spi.c
Allow direct setup of SPI pins through per project board_config.h
JIRA: NIL-422
=> imxrt-multi: Add board_config.h for spi

sensors/simsensor_common/simsensor_reader.c
This PR adds parsing all types of sensors, which are currently supported.
More flexing ability to test programs, which uses sensors data,
=> Add parsing all sensors types in simsensor

adc/ad7779/ad7779-driver.c
=> ad7779: fix priority argument

sensors/Makefile, sensors/baro/baro_sim.c, sensors/gps/gps_sim.c, sensors/imu/imu_sim.c, sensors/mag/mag_sim.c, sensors/simsensor_common/event_queue.c, sensors/simsensor_common/event_queue.h, sensors/simsensor_common/simsensor_generic.c, sensors/simsensor_common/simsensor_generic.h
This PR provides implementation for mocking sensors readings for all supported sensors types.
Easier testing programs, which uses sensors.
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/361
=> Add simsensors

spi/imx6ull-qspi/qspi.c, spi/imx6ull-qspi/qspi.h, storage/imx6ull-flashnor/Makefile, storage/imx6ull-flashnor/flashnor-drv.c, storage/imx6ull-flashnor/flashnor-qspi.c, storage/imx6ull-flashnor/flashnor.c, storage/imx6ull-flashnor/nor/nor.c, storage/imx6ull-flashnor/nor/nor.h
=> imx6ull-flashnor: add jffs2 and root mounting support

cpu/imxrt117x-cm4/imxrt117x-cm4.c
- add custom vector table offset
- reset M4 core only
JIRA: NIL-107
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/176
=> imxrt117x-cm4: small improvements

.gitignore, _targets/Makefile.sparcv8leon3-gr716, tty/gr716-uart/Makefile, tty/gr716-uart/gr716-uart.c
implement uart driver for GR716
JIRA: RTOS-363
=> implement uart driver for GR716

storage/imxrt-flash/flashdrv.c
=> imxrt-flash: fix erased sector buffer check

sensors/include/libsensors.h
This PR allows to compile `libsensors` library on host. Previous compilation was impossible, because of different definition place of `time_t` type. Now `time.h` header is added, which according to POSIX shall define this type.
Enable compilation on host for testing purposes and faster development cycle.
=> Enable `libsensors` compilation on host

sensors/simsensor_common/simsensor_generic.c, sensors/simsensor_common/simsensor_reader.c
PR fixes simsensors behavior. Invalid thread end was fixed in generic simsensor as well as wrong endline character handling in reader.
Bug fix. More robust interface to work with.
=> Fix simsensors

spi/common/libspi-msg.c, spi/common/spi-msg.h, spi/zynq7000-spi/zynq7000-spi.c, spi/zynq7000-xspi/zynq7000-xspi.c
JIRA: RTOS-472
To avoid need to mmap memory for very small buffers
=> spi: Pack small data payload to msg raw fields

tty/gr716-uart/gr716-uart.c
=> gr716-uart: update uart frequency (PLL usage)

tty/imx6ull-uart/imx6ull-uart.c
=> uart-imx6ull: fix uart_close()

storage/imx6ull-flashnor/flashnor.c
=> imx6ull-flashnor: Fix args parsing

sensors/Makefile, sensors/mag/lis2mdl.c
JIRA: PP-159
Adding driver for lis2mdl 3 axis +-50gauss magnetometer.
Datasheet: https://www.st.com/resource/en/datasheet/lis2mdl.pdf
=> sensors: add lis2mdl magnetometer driver

sensors/Makefile, sensors/imu/lsm9dsxx.c, sensors/imu/mpu6000.c
Driver of `mpu6000` 6-axis gyroscope/accelerometer device. Communication via SPI.
Datasheet: https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Datasheet1.pdf
Register map: https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Register-Map1.pdf
=> sensors: add mpu6000 imu driver

sensors/imu/lsm9dsxx.c, sensors/imu/mpu6000.c, sensors/include/libsensors.h
Change in sensorhub accelerometer reading variable type from `int16_t` to `int32_t`. This increases maximum accelerometer value from small +-3G to more than +-200kG which is much more than sufficient.
=> sensors: int32 accelerometer reading

_targets/Makefile.sparcv8leon3-gr716, storage/gr716-flash/Makefile, storage/gr716-flash/flashdrv.c, storage/gr716-flash/flashdrv.h, storage/gr716-flash/flashsrv.c, storage/gr716-flash/gr716-flashsrv.h, storage/gr716-flash/nor/flash.h, storage/gr716-flash/nor/nor.c, storage/gr716-flash/nor/nor.h, storage/gr716-flash/spimctrl.c, storage/gr716-flash/spimctrl.h, storage/gr716-flash/tests/Makefile, storage/gr716-flash/tests/flashsrv_mfs_tests.c, storage/gr716-flash/tests/flashsrv_raw_tests.c, storage/gr716-flash/tests/tests.c, storage/gr716-flash/tests/tests.h, storage/gr716-flash/tests/utils.h
=> gr716: implement flash driver

multi/imxrt-multi/cm4/example/Makefile.ext, multi/imxrt-multi/cm4/example/blinky.sh, multi/imxrt-multi/cm4/lib/Makefile.ext
=> makes: fix build of CM4 example

storage/gr716-flash/flashsrv.c
Add necessary `break` in `rawThread`
JIRA: RTOS-536
=> gr716-flash: fix implicit fall through case

storage/pc-ata/ata.c, storage/pc-ata/ata.h
DONE: RTOS-576
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/262
=> pc-ata: Allow raw device/partition byte access

sensors/imu/mpu6000.c
JIRA: PP-171
Adding argument to driver start so it is selectable. No argument defaults to no filtering. Examples of correct arguments to mpu6000:
| Command                                    | spi device   | ss selection | lpf selection |
|--------------------------------------------|--------------|--------------|---------------|
|   `sbin/sensors -s mpu6000:/dev/spi0.2::3` |  /dev/spi0.2 | none         | 3             |
|   `sbin/sensors -s mpu6000:/dev/spi0.2`    |  /dev/spi0.2 | none         | 0 (default)   |
| `sbin/sensors -s mpu6000:/dev/spi0.2:1`    |  /dev/spi0.2 | 1            | 0 (default)   |
| `sbin/sensors -s mpu6000:/dev/spi0.2:1:4`  | /dev/spi0.2  | 1            | 4             |
mpu6000 has a low pass filter which offers good quality filtering.
=> mpu6000: add lpf selection argument

_targets/Makefile.sparcv8leon3-gr716, multi/gr716-multi/Makefile, multi/gr716-multi/adc.c, multi/gr716-multi/adc.h, multi/gr716-multi/common.h, multi/gr716-multi/gpio.c, multi/gr716-multi/gpio.h, multi/gr716-multi/gr716-multi.c, multi/gr716-multi/gr716-multi.h, multi/gr716-multi/spi.c, multi/gr716-multi/spi.h, multi/gr716-multi/uart.c, multi/gr716-multi/uart.h
=> gr716: implement multi driver

multi/gr716-multi/gpio.c
=> gr716-multi: remove unused variable

multi/stm32l1-multi/lcd.c
DONE: RTOS-597
Fixes https://github.com/phoenix-rtos/phoenix-rtos-devices/issues/84
=> stm32l1-multi/lcd: Fix buffer overflow

multi/imxrt-multi/cm4.c, multi/imxrt-multi/gpio.c, multi/imxrt-multi/i2c.c, multi/imxrt-multi/imxrt-multi.c, multi/imxrt-multi/spi.c, multi/imxrt-multi/trng.c
JIRA: NIL-441
Fix non-blocking read() & write() calls.
Non-blocking mode is used by serial device in core-libs.
=> imxrt-multi: support for non-blocking operations on CM4 devices

multi/gr716-multi/common.h
=> gr716-multi: bump sysclk frequency to 50MHz

multi/gr716-multi/adc.c, multi/gr716-multi/common.h, tty/gr716-uart/gr716-uart.c
=> gr716: use SYSCLK_FREQ defined in board_config

multi/stm32l4-multi/config.h, multi/stm32l4-multi/libmulti/include/libmulti/libdma.h, multi/stm32l4-multi/libmulti/include/libmulti/libuart.h, multi/stm32l4-multi/libmulti/libdma.c, multi/stm32l4-multi/libmulti/libspi.c, multi/stm32l4-multi/libmulti/libuart.c, multi/stm32l4-multi/tty.c, multi/stm32l4-multi/uart.c
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/395/
=> stm32: add DMA support to libuart

libpseudodev/Makefile, libpseudodev/pseudodev.c, libpseudodev/pseudodev.h, multi/gr716-multi/Makefile, multi/gr716-multi/gr716-multi.c, multi/gr716-multi/gr716-multi.h, multi/imxrt-multi/Makefile, multi/imxrt-multi/imxrt-multi.c, multi/imxrt-multi/imxrt-multi.h
This change adds the standard pseudo devices (as library) for small targets (without using posixsrv)
* `/dev/null`
* `/dev/zero`
* `/dev/full`
* `/dev/urandom`
First, I add the library use-cases to  the`imxrt10xx`, `imxrt117x` and `sparc-gr716` targets, because of the similar implementation of multi-driver.
Should work well with `psh` stream stdio redirections, try e.g.:
```bash
(psh)% dd < /dev/urandom > /dev/full
(psh)% dd count=1024 bs=1024 if=/dev/urandom > /dev/null
(psh)% dd if=/dev/zero of=/dev/null count=1024
```
```bash
(psh)% help &> /dev/null
(psh)% cat notexisting 2> /dev/null
```
=> Add pseudo devices on small targets

adc/ad7779/Makefile, adc/ad7779/ad7779-driver.c, adc/ad7779/ad7779-tool.c
- adc/ad7779: add commandline diagnostics tool
- adc/ad7779: add optional async requests support
Needed for ADC multi-access from several clients. By default disabled to keep
the same footprint on constrained devices not needed the functionality
JIRA: DTR-415
=> ad7779: concurrent access option & diagnostics tool

mag/Makefile, mag/mag-als31300.c
=> mag: add als31300 driver

tty/usbacm/usbacm.c
=> usbacm: fix close()

multi/gr716-multi/gr716-multi.c, multi/gr716-multi/uart.c
=> gr716-multi: configure by board_config

adc/ad7779/ad7779-tool.c
also: remove ifdefed code
JIRA: DTR-415
=> adc/ad7779: ad-tool: fix max value constraint

libklog/libklog.c, libklog/libklog.h, multi/gr716-multi/gr716-multi.c, multi/gr716-multi/gr716-multi.h, multi/gr716-multi/uart.c, multi/imxrt-multi/imxrt-multi.c, multi/imxrt-multi/imxrt-multi.h, tty/grlib-uart/grlib-uart.c, tty/imx6ull-uart/imx6ull-uart.c, tty/pc-tty/ttypc.c, tty/spike-tty/spike-tty.c, tty/uart16550/uart16550.c, tty/zynq7000-uart/zynq7000-uart.c
=> libklog: Add option to disable kmsg on the console

tty/grlib-uart/grlib-uart.c
Stack sizes weren't changed when adapting the driver to GR712RC target and are unnecessarily big.
=> grlib-uart: change stack sizes

tty/usbacm/usbacm.c
- fix resource leak (always creating resources on open())
- fix memory leak (always allocating FIFO on open())
- fix blocking open() after non-blocking open()
- remove unused fields from usbacm_dev_t struct
- remove dead code
- handle device disconnection while reading
- bubble up errors from sub-procedures
JIRA: DTR-348
=> tty/usbacm: refactor

multi/grlib-multi/uart.c, tty/grlib-uart/grlib-uart.c
=> grlib/uart: clear buffer before initialization

multi/grlib-multi/Makefile, multi/grlib-multi/grlib-multi.c, multi/grlib-multi/grlib-multi.h, multi/grlib-multi/spacewire.c, multi/grlib-multi/spacewire.h
=> grlib-multi: implement SpaceWire driver

storage/imx6ull-flash/flashdrv.c, storage/imx6ull-flash/imx6ull-flash-test.c, storage/imx6ull-flash/imx6ull-flashdrv.h
Detect and handle multi-chip Kioxia TH58NV 16Gbit NAND
=> imx6ull-flash: Handle multi-chip NANDs

otp/imx6ull-otp/imx6ull-otp.c
Also: add arbitrary address readout for low-level access
JIRA: DTR-467
=> imx6ull-otp: add hw revision register to OTP

mag/mag-als31300.c
Read registers 0x28 and 0x29 together to avoid combining two different samples.
JIRA: DTR-445
=> mag: fix value reading

storage/gr712rc-flash/flashsrv.c
JIRA: RTOS-735
Not really _that_ needed but why not
=> gr712rc-flash: free memory when init fails

multi/stm32l4-multi/tty.c
=> stm32l4-multi: add mask for reading bytes of size 7 and 6  from tty

multi/stm32l4-multi/rng.c, multi/stm32l4-multi/rng.h, multi/stm32l4-multi/stm32l4-multi.c, multi/stm32l4-multi/stm32l4-multi.h
=> stm32l4-multi: Add RNG driver

tty/uart16550/uarthw-riscv.c
=> uart16550/riscv: use info from board_config

multi/stm32l4-multi/libmulti/include/libmulti/libuart.h, multi/stm32l4-multi/libmulti/libuart.c
This change provide to improvement to libuart DMA code:
1. Adding missing volatile specifier for pointer that's used to synchronisation between interrupt and reader code
2. Removing modulo from interrupt code, what potentially can speedup execution
I found that sometimes I got following result when stressing up this driver:
Received pattern:
```
00155718_ABCDEFGHIJKLMNOPQRSTUVWXY\
00WXY\19_ABCDEFGHIJKLMNOPQRSTUVWXY\
00155720_ABCDEFGHIJKLMNOPQRSTUVWXY\
```
Expected pattern:
```
00155718_ABCDEFGHIJKLMNOPQRSTUVWXY\
00155719_ABCDEFGHIJKLMNOPQRSTUVWXY\
00155720_ABCDEFGHIJKLMNOPQRSTUVWXY\
```
(new lines replaced with \ for readability)
Code analysis make me find missing volatile for pointer. But it's not resolve the issue.
I found that this issue is not connected with overrun detected by the …
=> stm32l4x6-multi: improve libuart DMA

adc/ad7779/ad7779-driver.c, adc/ad7779/ad7779.c, adc/ad7779/ad7779.h, adc/ad7779/adc-api-ad7779.h
=> adc/ad7779: add support for setting DOUT drive strength

multi/stm32l4-multi/libmulti/libuart.c
Optimize `libuart_infiniteRxHandler`:
- return early when `rxbuf` is `NULL` - previously the function updated positions in buffer even when no one was waiting to read from UART. This caused us to unnecessary execute most of the interrupt handling code, which probably resulted in delay of interrupt handling when `rxbuf` was ready. This early return fixes the problem with overrun.
- for safety, swapped `memcpy` to `for` loop on volatile DMA buffer.
- check if in IDLE interrupt we have any new data to receive - previously handler was entered even without any data ready which also introduced additional delay in processing interrupts from DMA
Examples from testing:
```
00000384_ABCDEFGHIJKLMNOPQRSTUVWXYZ123469
00000385_ABCNOPQRSTUVWXYZ123469
00000386_ABCDEFGHIJKLMNOPQRSTUVWXYZ123469
```
In 385 …
=> stm32l4-multi/libuart: optimize infiniteRxHandler

multi/stm32l1-multi/spi.c, multi/stm32l1-multi/spi.h, multi/stm32l4-multi/i2c.c, multi/stm32l4-multi/i2c.h, multi/stm32l4-multi/spi.c, multi/stm32l4-multi/spi.h, storage/imx6ull-flash/flashsrv.c, storage/umass/umass.c, tty/usbacm/usbacm.c
=> fix warnings

multi/stm32l4-multi/stm32l4-multi.c
Fix open() not working on /multi. Move file to /dev
msg API change revealed a problem with open() on "files" created via portRegister. These files need to handle stat(), so getAttr msg correctly. This change fixes the root of the problem instead, i.e. using portRegister to create special files is no longer valid, so it shouldn't be done
DONE: RTOS-805
=> !stm32l4-multi: Create iface special file using create_dev

storage/gr716-flash/Makefile, storage/imx6ull-flashnor/Makefile, storage/imxrt-flash/Makefile
=> Add libtinyaes required by meterfs

storage/imxrt-flash/flashsrv.c
Fixes the following:
`portRegister()` is called twice per `meterfs` partition entry. For the first time right after `portCreate()`, and second time inside the `create_dev()` - this causes ports to be assigned incorrectly.
JIRA: RTOS-807
=> imxrt-flash: remove redundant portRegister

tty/usbacm/usbacm.c
=> tty/usbacm: Fix warning

multi/stm32l4-multi/config.h, multi/stm32l4-multi/stm32l4-multi.c
Interface thread number can be set via board_config.h
JIRA: DEND-319
With excecive communication via two uarts (RX/TX) it looks like other interfaces starving. Not sure if adding interface thread solve anything or this is just clock issue, however possibility to tune number of interface threads is nice addition that is worth to be checked.
=> stm32l4-multi: Add configuration of interface thread number

storage/gr716-flash/flashsrv.c, storage/imxrt-flash/flashsrv.c
lseek expects atSize attribute be available on block devices via mtGetAttr message. Fix missing handlers
=> storage: Add missing mtGetAttr handlers

storage/imxrt-flash/flashdrv.c, storage/imxrt-flash/flashsrv.c, storage/imxrt-flash/fspi.h
Add support for second flash memory.
https://github.com/phoenix-rtos/plo/pull/330
=> imxrt-flash: support for second flash memory

multi/stm32l4-multi/libmulti/include/libmulti/libdma.h, multi/stm32l4-multi/libmulti/libdma.c, multi/stm32l4-multi/libmulti/libuart.c, multi/stm32l4-multi/tty.c
=> Improve UART/DMA on stm32l4-multi

storage/imxrt-flash/flashdrv.c, storage/imxrt-flash/flashdrv.h, storage/imxrt-flash/flashsrv.c, storage/imxrt-flash/fspi.c, storage/imxrt-flash/fspi.h, storage/imxrt-flash/imxrt-flashsrv.h, storage/imxrt-flash/nor.c
=> imxrt-flash: non-XIP flash ops don't block XIP threads

multi/imxrt-multi/cm4.c
=> imxrt-multi: fix loadFromFile()

dma/grdmac2/grdmac2.c, multi/grlib-multi/adc.c, multi/grlib-multi/gpio.c, multi/grlib-multi/spacewire.c, multi/grlib-multi/spi.c, multi/grlib-multi/uart.c, storage/gr716-flash/spimctrl.c, tty/grlib-uart/grlib-uart.c
=> grlib drivers: name union in platformctl_t

multi/imxrt-multi/imxrt-multi.c
Stack was overwritten by CM4 loadFromFile().
JIRA: RTOS-853
=> imxrt-multi: increase msg thread stack size to 1024

_targets/Makefile.armv8r52-mps3an536, tty/cmsdk-apbuart/Makefile, tty/cmsdk-apbuart/cmsdk-apbuart.c
=> add armv8r52-mps3an536 uart driver

storage/imxrt-flash/nor.c
=> imxrt-flash: Support W25Q512NW-IQ/IN flash chips

storage/pc-ata/ata.c
=> pc-ata: fix index bound in pci dev iteration

_targets/Makefile.sparcv8leon-generic, _targets/Makefile.sparcv8leon-gr712rc, _targets/Makefile.sparcv8leon-gr716, dma/grdmac2/grdmac2.c, multi/grlib-multi/adc.c, multi/grlib-multi/gpio.c, multi/grlib-multi/spacewire.c, multi/grlib-multi/spi.c, multi/grlib-multi/uart.c, storage/gr716-flash/spimctrl.h, tty/grlib-uart/grlib-uart.c
JIRA: RTOS-883
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/229
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/520
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/141
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/617
https://github.com/phoenix-rtos/libphoenix/pull/390
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/217
https://github.com/phoenix-rtos/plo/pull/366
=> rename sparcv8leon3 to sparcv8leon

multi/imxrt-multi/config.h, multi/imxrt-multi/gpio.c, multi/imxrt-multi/gpio.h, multi/imxrt-multi/imxrt-multi.c, multi/imxrt-multi/uart.c
Disable receiver while transmission is in progress. Toggle GPIO in software when switching between transmit and receive mode.
This feature can be configured by adding a new line to `board_config.h` like this:
```
#define UART12_HALF_DUPLEX_GPIO .port = 4, .pin = 27, .onTx = 1
```
This results in signal `GPIO_MUX4_IO27` being manipulated, high state is output when transmitting and low when ready to receive. `.onTx = 0` would result in low state being output when transmitting and high when ready to receive.
=> imxrt-multi: implement software controlled half-duplex UART

sensors/simsensor_common/simsensor_reader.c
=> sensors/simsensors: fix strtoll error check

usb/ehci/ehci.c
=> usb/ehci: add option to set irqthread priority by board_config.h

tty/libtty/libtty.h, tty/libtty/libtty_disc.c, tty/libtty/libtty_disc.h
=> libtty: adapt to new location of _POSIX_VDISABLE

tty/uart16550/uart16550.c
This commit extends allowable range of baudrates accepted by uart16550 driver from 115200 to 460800.
This extension was needed for the purpose of Processor-in-the-loop implementation on zynq7000 platform. Maximum baudrate of 115200 caused significant delay in data frames transmission.
=> tty: extend baudrate limit checked in set_baudrate()

libklog/libklog.c, libklog/libklog.h, tty/pc-tty/ttypc.c, tty/uart16550/uart16550.c
JIRA: RTOS-998
https://github.com/phoenix-rtos/libphoenix/pull/403
=> tty: add option to not register as a console

tty/pc-tty/ttypc.c, tty/uart16550/uart16550.c
=> tty: misc fixes post gcc 14.2

_targets/Makefile.armv7r5f-zynqmp
=> _targets: add armv7r5f-zynqmp target

tty/zynq-uart/zynq-uart.c
Added support for routing console UART via PL (programmable logic) subsystem
=> zynqmp: console routing via PL

_targets/Makefile.aarch64a53-zynqmp, can/zynqmp-can/Makefile, can/zynqmp-can/README.md, can/zynqmp-can/zynqmp-can-if.c, can/zynqmp-can/zynqmp-can-if.h, can/zynqmp-can/zynqmp-can-priv.h, can/zynqmp-can/zynqmp-can-test.c, can/zynqmp-can/zynqmp-can.c
Created a simple ZynqMP CAN driver. 
Support of CAN peripheral in Zynq Ultrascale devices
- [] This PR needs additional PRs to work:
=> zynqmp: add CAN driver

multi/mcxn94x-multi/Makefile, multi/mcxn94x-multi/cpu.c
JIRA: RTOS-1044
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/648
=> mcxn94x-multi: Add cpu (mailbox) driver

_targets/Makefile.aarch64a53-zynqmp, tty/uart16550/Makefile, tty/uart16550/uarthw-zynq.c
Changes:
- add support for uart16550 driver on zynqmp platform
- make former zynq7000 driver generic for both platforms
JIRA: PP-268
=> zynqmp: add uart16550 support

sensors/include/libsensors.h
This commit provides basic structures and definitions for new sensor types: differential barometer and generic sensor providing EKF state.
This change is required to extend support of Phoenix autopilot to fixed-wing platforms.
=> sensors: add support for differential barometer and EKF sensors

_targets/Makefile.aarch64a53-zynqmp, _targets/Makefile.armv7a9-zynq7000, i2c/zynq/Makefile, i2c/zynq/libzynq-i2c.c, i2c/zynq/zynq-i2c.c
Generalized zynq7000 i2c driver to use it in zynqmp
JIRA: PP-289
=> zynqmp: add i2c driver

adc/ad7779/ad7779-tool.c
Current configuration might be different than the default one.
JIRA: DTR-500
=> adc/ad7779: tool: use real channel gain for DC offset estimation

adc/ad7779/ad7779-tool.c
Cherry-pick fixes from master branch into the 3.3 release branch:
- adc/ad7779: tool: use real channel gain for DC offset estimation
=> Cherry-pick changes for release 3.3

_targets/Makefile.riscv64-gr765, _targets/Makefile.riscv64-grfpga
=> rename noelv to grfpga, add riscv64-gr765 target

gpio/imx6ull-gpio/imx6ull-gpio.c
=> gpio: imx6ull: optimize access control

multi/imxrt-multi/uart.c
Interrupt mask for RX interrupts was lifted in the interrupt handler and only re-applied in the reaper thread, allowing for a higher-priority thread to potentially interfere, leading to losing characters because of the interrupt not going off.
Fixes phoenix-rtos/phoenix-rtos-project#1310
=> imxrt-multi/uart: fix HW RX overrun

multi/grlib-multi/uart.c, tty/grlib-uart/grlib-uart.c
=> grlib-uart: optimize interrupt thread

_targets/Makefile.aarch64a53-zynqmp
JIRA: PP-362
Adding sensors components to build process of zynqmp platform
=> zynqmp: add libsensors component

sensors/client-include/libsensors/client.h
=> libsensors/client.h: add definitions of star tracker and FSS sensors
