phoenix-rtos/phoenix-rtos-devices

tty/pc-tty/ttypc.c
tty/pc-tty/ttypc.h
tty/pc-tty/ttypc_kbd.c
tty/pc-tty/ttypc_kbd.h
tty/pc-tty/ttypc_vga.c
tty/pc-tty/ttypc_virt.c
tty/pc-tty/ttypc_virt.h
tty/pc-tty/ttypc_vtf.c
tty/pc-uart/pc-uart.c

Changes based on pc-uart's usage of libtty. Fields ttypc_virt_t::m_echo and ttypc_virt_t::m_mln were removed since echo and feed line termios options are handled by libtty.

Integrate libtty into pc-tty

---

storage/pc-ata/atasrv.c

- -p option: unneccessary typecasting
- -r option: one argument provides `r:`
- -h option: should exit, not continue

atasrv: fixed parsing options

---

adc/ad7779/ad7779-driver.c
display/oled-128O064B0/oled-dev.c
dma/imx6ull-sdma/imx6ull-sdma.c
gpio/imx6ull-gpio/imx6ull-gpio.c
multi/imxrt-multi/imxrt-multi.c
multi/stm32l1-multi/stm32-multi.c
multi/stm32l4-multi/stm32-multi.c
storage/imx6ull-flash/flashsrv.c
storage/imxrt-flash/flashsrv.c
tty/imx6ull-uart/imx6ull-uart.c

Accordingly to https://github.com/phoenix-rtos/libphoenix/issues/70#issuecomment-697253799

Unify use of the rid parameter of msgRecv, msgRespond functions

---

storage/imx6ull-flash/flashsrv.c

This commit fixes typo described in code review https://github.com/phoenix-rtos/phoenix-rtos-devices/commit/1bf9f02721989066452f254c0e0ea29ed3a6d99c#r42685130 and refer to https://github.com/phoenix-rtos/libphoenix/issues/70

flashsrv: Fix typo introduced with commit #1bf9f02

---

multi/imxrt-multi/imxrt-multi.c

This fix is about the issue https://github.com/phoenix-rtos/phoenix-rtos-devices/issues/61

imxrt-multi: Fix unexpected behaviour if SPI4 entry is created

---

multi/stm32l1-multi/Makefile
multi/stm32l1-multi/README.md
multi/stm32l1-multi/dma.c
multi/stm32l1-multi/dma.h
multi/stm32l1-multi/spi.c
multi/stm32l1-multi/stm32-multi.c
multi/stm32l1-multi/stm32-multi.h
multi/stm32l4-multi/Makefile
multi/stm32l4-multi/README.md
multi/stm32l4-multi/dma.c
multi/stm32l4-multi/dma.h
multi/stm32l4-multi/spi.c
multi/stm32l4-multi/stm32-multi.c
multi/stm32l4-multi/stm32-multi.h

This change introduces DMA to stm32lx-multi driver (both STM32L1 and STM32L4 are supported). Currently only SPI peripheral is handled, avoiding the overhead of sharing DMA channels between multiple peripherals. DMA transfers are used implicitly by the driver when a certain transfer length threshold is exceeded - processes using multi driver have no notion of DMA at all.
Hardware NSS output is now enabled, eliminating the need of managing NSS GPIO in software. The pin still needs to be explicitly mapped as alternate function, so the change is backward compatible. NSS is always asserted when SPI peripheral is enabled, so the enable/disable part has to be done directly before and after the transaction.
The following enhancements, which may be added to this request, are to be discussed:
- …

stm32lx-multi: Add DMA support, make SPI use DMA

---

multi/stm32l1-multi/rtc.c
multi/stm32l4-multi/rtc.c

Fix issue of cutting off high part of seconds in set.
This causing an issue where time was not properly set
Eg. ts 1601907525 
GMT: Monday, 5 October 2020 14:18:45
was set as
GMT: Monday, 5 October 2020 14:18:05
Tested on stm32l4, checked in documentation that it should be apply also to l1

stm32lX-multi: Fix setting time on RTC

---

multi/stm32l1-multi/exti.c
multi/stm32l1-multi/stm32-multi.c
multi/stm32l4-multi/exti.c
multi/stm32l4-multi/exti.h
multi/stm32l4-multi/rtc.c
multi/stm32l4-multi/rtc.h
multi/stm32l4-multi/stm32-multi.c
multi/stm32l4-multi/stm32-multi.h

This change introduces settable alarms to multidrv. For now only alarm A is supported.
Accompanied by the resolution increase PR:
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/150

stm32lx-multi: Support setting up precise RTC alarms

---

multi/imxrt-multi/Makefile

This fixes the error that is possible at compile time if the `-j` option is used.

imxrt-multi: added uart.c dependency on libtty.h

---

.github/workflows/ci.yml

Adding basic CI build test - every commit/pull request will be checked against building within `phoenix-rtos-project` repo. To be more specific: `phoenix-rtos-project:HEAD` with one submodule updated (`phoenix-rtos-devices`) to the offending commit (either branch:HEAD or PR:HEAD).
The same changes will soon follow in other repos.

ci: add basic CI checks against phoenix-rtos-project

---

Makefile

This PR makes it possible to call
```bash
make -C phoenix-rtos-devices adc/ad7779
```
instead of
```bash
make -C phoenix-rtos-devices all adc/ad7779
```
which is more semantic, as this invocation builds only `adc/ad7779` component anyway.

make: add option to build specific target without adding 'all' target

---

multi/stm32l4-multi/Makefile

`libstm32l4-multi.a` does not depend on `libtty.h`.
`tty.o`. depends on `libtty.h`.
Can be removed `$(SRCHEADERS)` in a line
```
$(MULTIDRV_OBJS): $(SRCHEADERS) $(PREFIX_H)libtty.h
```

stml24-multi: corrected dependency

---

multi/imxrt-multi/config.h
multi/imxrt-multi/uart.c

The default baudrate equals 115200. Optional values set as UARTX_BAUDRATE.

imxrt: add optional baudrate defines

---

multi/stm32l4-multi/config.h
multi/stm32l4-multi/stm32-multi.c
multi/stm32l4-multi/tty.c

Currently logs are always sent to TTY when any TTY is enabled. After this change TTY can be used (ie. for optoport) without log redirection.
I've checked stm32l4 projects on gerrit and this would not change current behavior.

stm32l4_tty: send logs to tty only when UART_CONSOLE points to tty

---

multi/stm32l1-multi/uart.c
multi/stm32l4-multi/libmulti/libuart.c
multi/stm32l4-multi/tty.c

Added the static keyword to eliminate copying the structure to the stack.

multi: added the static keyword

---

adc/ade7913/ade7913-test.c
adc/ade7913/ade7913.c

ADE7913 devices can be connected to SPI CS pins in many different
orders, thus giving CS pin orders as argument like:
ade7913-test;2301 - means main ADE7913 device (source of the clock)
is connected to CS pin 2, next in chain is connected to CS
pin 3, etc. This argument ensures correct initialization.
JIRA: NIL-117

ade7913: add CS pins ordering as arg, fix power enable

---

multi/imxrt-multi/imxrt-multi.c

JIRA: RTOS-68
Fixes behavior of `imxrt-multi` device registration when a directory `/dev` already exists.
`mkdir()` returns `-1` and sets `errno` value  respectively, checking returned value if it is -EEXIST or not is not correct.

imxrt-multi: fix errno check for already exist dir

---

tty/uart16550/uart16550.c
tty/uart16550/uart16550.h

Fixed following issues:
- all UART devices used the same path ("/dev/ttyS0") for port registration,
- device oid passed to portRegister() wasn't initialized,
The uart16550 didn't work on real PC hardware.
[JIRA: PD-86](https://jira.phoenix-rtos.com/browse/PD-86)

uart16550: fix device ports registration

---

multi/stm32l4-multi/stm32l4-multi.c
multi/stm32l4-multi/tty.c

Due to recent changes, stm32l4-multi driver starts to overflow stack.
Values are chosen to reflect current stack size usage.
JIRA: ISM-53
Stack size changes to avoid stack overflows. Probably caused by recent changes in libphoenix, but not sure.
I found that current worst case scenario for stack is:
| entry point | previous stack | current stack | stack usage |  
| --- | --- | --- | --- |
| tty_irqthread |  256 | 512 | 336 |
| tty_thread  |  512 | 768 | 608 |
| thread | 512 | 640 | 440 |
(stack usage is estimated without cost of interrupts and syscall call)
So this change increase memory usage by 256 + 256 * 3 +  128 * 2 = 1280 B
Compile and program with DEBUG kernel before and after the change.  It stops detects stack overflows.

stm32l4-multi: Increase stack size

---

storage/imx6ull-flash/Makefile
storage/imx6ull-flash/flashdrv.c
storage/imx6ull-flash/flashsrv.c
storage/imx6ull-flash/imx6ull-flash-test.c
storage/imx6ull-flash/imx6ull-flashdrv.h
storage/imx6ull-flash/imx6ull-flashsrv.h
storage/imx6ull-nandtool/bcb.h
storage/imx6ull-nandtool/nandtool.c
storage/imx6ull-nandtool/test.c

This (and connected PRs) are needed to:
- support various NAND flash types dynamically (runtime detection)
- actually manage badblocks correctly
DTR-88
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/121
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/43
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/79

NAND flash support enhancements

---

tty/imx6ull-uart/imx6ull-uart.c

JIRA: RTOS-76
Fix base address of uart8.
According to reference manual, current address `0x02284000` of `uart8` points to Random Number Generator instead of uart controller.
Proper uart's address can be found on page `3614` in:
**i.MX 6ULL Applications Processor Reference Manual, Rev. 1, 11/2017**

uart-imx6ull: fix base address of uart8

---

storage/pc-ata/mbr.h

JIRA: RTOS-21
This PR make mbr_t structure packed.
Making the `mbr_t` structure packed would simplify mbr parsing/writing by allowing to cast a data buffer to `mbr_t` pointer. The `pentry_t` structure defined above contains the `packed` attribute, so for consistency `mbr_t` should also be packed.

pc-ata: Make mbr_t structure packed

---

storage/imx6ull-flash/flashdrv.c
storage/imx6ull-flash/flashsrv.c
storage/imx6ull-flash/imx6ull-flash-test.c
storage/imx6ull-nandtool/bcb.c
storage/imx6ull-nandtool/nandtool.c
storage/imx6ull-nandtool/test.c

Changed DMA buffers allocation to OID_CONTIGUOUS allocator.
[JIRA: DTR-123](https://jira.phoenix-rtos.com/browse/DTR-123)

imx6ull-flash/imx6ull-nandtool: allocate physically contiguous DMA buffers

---

watchdog/imx6ull/watchdog.h

JIRA: DTR-122
Calling `ioctl(fd, WDIOC_KEEPALIVE, 0)` causes an exception in [processing ioctl response](https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/4167188a695efba62e561f1f528a471be8db325a/posix/posix.c#L1421). The data is NULL but size is 4 bytes. Change IO operation to void.

imx6ull: change watchdog api

---

dma/imxrt-edma/imxrt-edma.c
multi/imxrt-multi/imxrt1170.h
multi/imxrt-multi/spi.c

This change is intended to make the `imxrt1176` SPI driver behave similar to SPI driver on `imxrt1064` target (clock setup).
Additionally this PR fixes poor eDMA performance on `imxrt1176`.
JIRA: NIL-139, NIL-140
The imxrt-multi implementation on imxrt117x resets the default SPI clocks settings while turning on, this is different from the imxrt1064 implementation, where the clocks when turned on do not affect the rest of the configuration, i.e. dividers, multipliers, PLL's, etc.
A similar bug has also occurres in eDMA library and this PR fixes it.

imxrt1170: quickfix of SPI and eDMA clock performance

---

storage/imx6ull-flash/flashsrv.c

Fixed erasing blocks outside of partition range for `start > 0` and `size = 0`.
[JIRA: RTOS-96](https://jira.phoenix-rtos.com/browse/RTOS-96)
The problem showed up while testing blocks erasure with `nandtool`.

imx6ull-flash: fix erase size in flashsrv_devErase()

---

multi/imxrt-multi/Makefile
multi/imxrt-multi/config.h
multi/imxrt-multi/imxrt-multi.c
multi/imxrt-multi/imxrt-multi.h
multi/imxrt-multi/imxrt1060.h
multi/imxrt-multi/trng.c
multi/imxrt-multi/trng.h

JIRA: BES-180
This change adds the True Random Number Generator driver for imxrt106x and imxrt105x.
This change is needed in order to provide a reliable source of entropy for applications using secure protocols, such as SSL. The interface for the driver is a dev file `/dev/trng`. Client applications should communicate with it using msg API and `multi_i_t` structure. For now it is not possible to communicate with the multidriver using open()/read()/write() syscalls. Therefore I decided not to name the file `/dev/random`, as it might be misleading.

imxrt-multi: Add TRNG driver

---

gpio/imx6ull-gpio/README.md
gpio/imx6ull-gpio/imx6ull-gpio.c

We need easy way to toggle leds from shell scripts. This is a kind-of hackish approach (single file which understands `text` and `binary` write mode), but I can use other approach if preferable:
- separate files for `text mode` (`textdir`, `textport`? :rofl:)
- `export` file which would allow us to dynamically export specific pin from specific port as a dir with files for different options (the linux way)
For now went whit the easiest path without creating additional files at all.
The `dir` and `port` files support text write mode for easier usage from shell scripts.
The syntax is `[+/-][pin]`, eg `+28`, `-7`, where:
- `+` means _value high_ for `port` and _output_ for `dir`
- `-` means _value low_ for `port` and _input_ for `dir`
- `pin` is the numeric pin value in <0, 31> range
This …

imx6ull-gpio: add text write mode

---

multi/stm32l4-multi/libmulti/libi2c.c
multi/stm32l4-multi/libmulti/libi2c.h

JIRA: ISC-141
Added timeout for waiting for I2C interrupt
Faulty or not present device will cause interrupt to never come - previously will cause multidrv thread to deadlock forever.

stm32l4-multi/i2c: Fixed deadlock when device is not present or faulty

---

multi/imxrt-multi/config.h
multi/imxrt-multi/uart.c

Use speed_t type only, when communicating with libtty. Internally use
a plain uint32_t.
JIRA: RTOS-122
This change allows setting uart baudrate through BOARD_CONFIG using integer values instead of speed_t. Thanks to this change we can set uart baudrate in plo, kernel and in imxrt-multi using the same value without the need for any conversion. It makes setting uart baudrate less error prone.
In all projects using imxrt-multi, which set the baudrate value through BOARD_CONFIG, we shall change the values from speed_t to integer.

imxrt-multi: Use integer values for setting uart baudrate

---

multi/imxrt-multi/spi.c

JIRA: RTOS-126
Daisy chain definitions for SPI on imxrt targets are incorrect for a few inputs, according to the reference manuals.

imxrt-multi: Fix incorrect daisy definitions for spi

---

storage/imx6ull-flashnor/flashnor-ecspi.c

Removed `flashnor_escpiEraseChip()` as it's not needed anymore.
[JIRA: DTR-184](https://jira.phoenix-rtos.com/browse/DTR-184)
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/54

imx6ull-flashnor: remove partitionErase() usage

---

storage/imx6ull-flashnor/flashnor.c

Added setting `msg.o.lookup.fil.port` for `meterfs_handler()` mtLookup request.
[JIRA: DTR-183](https://jira.phoenix-rtos.com/browse/DTR-183)

imx6ull-flashnor: fix meterfs_handler() not setting msg.o.lookup.fil.port for mtLookup message

---

tty/libtty/libtty_disc.c

`condWait` takes timeout in microseconds, not in milliseconds
JIRA: DTR-197

libtty: fix VTIME timeout value

---

multi/stm32l4-multi/libmulti/libspi.c
multi/stm32l4-multi/libmulti/libspi.h

Interrupt waiting causes unneded overhead on operation that last for
some cycles
JIRA: ISC-154
Remove interrupt in libspi and a little cleanup
Many spi interrupts causes overhead that can cause invalid work of uart due to overrun. Proposed fix will avoid that issue

stm32l4-multi/libspi: Remove interrupt waitng

---

adc/ad7779/ad7779.c

Currently, if the channel is disabled, the header of sample is empty. Turn on the crc mode to keep channel number in the header even if it's disabled.

ad7779: turn on crc in the sample header

---

storage/imx6ull-flash/flashdrv.c
storage/imx6ull-flash/flashsrv.c
storage/imx6ull-flash/imx6ull-flash-test.c

Passing `aux == NULL` to `flashdrv_write()` means that we're going to perform partial page programming (data only). Therefore not programmed area (metadata and its ECC) should be set to `0xff`.
We trick BCH controller into thinking that this area contains metdata only without ECC (so that BCH won't calculate new ECC for the metadata).
[JIRA: DTR-109](https://jira.phoenix-rtos.com/browse/DTR-109)

imx6ull-flashsrv: fix flashsrv_write() overwriting metadata

---

multi/stm32l4-multi/stm32l4-multi.c
multi/stm32l4-multi/tty.c
multi/stm32l4-multi/tty.h

tty devices was not available on /dev
This commit fixes that
It's quite complicated because:
- Port for main console have to be first registered port (depending on configuration it's tty or multidrv port)
- Rootfs have to be initialized before tty want's to create dev on it
- tty will not work if rootfs is not created (it's not possible to create entries in /dev then)
Required for use open("/dev/uartX') in application code again, after posixifyizing open on stm32l4. 
psh run on target. Directory /dev appeared with tty, uart1 and uart3 files.

stm32l4-multi: Use create_dev for tty devices

---

storage/host-flash/host-flash.c
storage/host-flash/host-flash.h
storage/imxrt-flash/flashsrv.c

Adapted to change in meterfs
JIRA: DTR-179

host-flash, imxrt-flash: Added missing const to write callbacks

---

multi/stm32l4-multi/adc.c

JIRA: SKAL-420
Some ADC operations are very fast and reschedule is really just in case. ADC channel probing takes about 1-2 ms, so sleep is a good idea after all.

stm32l4-multi/adc: Added sleep during ADC probe

---

usb/ehci/ehci.c
usb/ehci/ehci.h

Save qtd physical address to avoid calling va2pa() every time.
Move the queue forward, when it gets stuck due to hardware racing
with ehci_enqueue() function.
JIRA: DTR-227
It fixes an issue, when new transfers are being enqueued constantly and they tend to race with the hardware.
When executing transfers, ehci fetches first qtd from the queue by copying it to an "overlay area" in a Queue Head structure. It then performs a transfers and afterwards saves the modifications back in the original qtd and follows the `next` pointer from the overlay area. If we modify a qtd that is now being processed in the overlay area, the controller won't see the modifications. If the modification is based on updating the `next` pointer it causes the queue to get stucked. This commit fixes this situation.

usb/ehci: Fix qtds management

---

storage/imx6ull-flashnor/flashnor.c

Changed printing errors to stdout instead of stderr. Replaced error numbers by their names with `strerror()` usage.
[JIRA: DTR-292](https://jira.phoenix-rtos.com/browse/DTR-292)

imx6ull-flashnor: print error logs on stdout

---

storage/imx6ull-flash/README.md
storage/imx6ull-flash/flashdrv.c
storage/imx6ull-flash/flashsrv.c
storage/imx6ull-flash/imx6ull-flash-test.c
storage/imx6ull-flash/imx6ull-flashdrv.h

Performance optimization. DMA descriptors and flash commands buffer physical address can be calculated using an offset from the beginning of the DMA buffer page (`flashdrv_dmaBuff_t`) which reduces number of `va2pa()` calls while creating a DMA descriptor chain.
[JIRA: DTR-169](https://jira.phoenix-rtos.com/browse/DTR-169)

imx6ull-flash: reduce number of va2pa() calls while creating DMA descriptor chains

---

storage/imx6ull-flash/flashdrv.c

Adjusted GPMI timings and configuration. Applied timings were checked against supported Micron and Kioxia chips.
Clock on the NAND chip pins above 33 MHz (in our case it's ~40 MHz - GPMI clock divided by data setup and data hold cycles so 198 / (3 + 2)) allows for enabling EDO mode which slightly improves NAND read speed.
[JIRA: DTR-169](https://jira.phoenix-rtos.com/browse/DTR-169)

imx6ull-flash: adjust GPMI configuration, enable EDO mode (DLL)

---

storage/imx6ull-flash/flashdrv.c

Changed GPMI NAND timinigs. Previous timings turned out to be too aggressive causing NAND driver to hang after few hours.
[JIRA: DTR-169](https://jira.phoenix-rtos.com/browse/DTR-169)

imx6ull-flash: relax GPMI NAND address setup and data setup timings

---

usb/ehci/ehci-hub.c
usb/ehci/ehci.c
usb/ehci/ehci.h

JIRA: DTR-227
When using edge triggered interrupts (e.g. on imx6ull) it is possible to lose interrupts in ehci controller by leaving an interrupt not acknowledged. In some rare cases it might cause the Asynchronous Schedule to get stuck.

usb/ehci: Fix irqs handling

---

storage/zynq7000-flash/Makefile
storage/zynq7000-flash/flashcfg.c
storage/zynq7000-flash/flashdrv.c
storage/zynq7000-flash/flashdrv.h
storage/zynq7000-flash/tests/Makefile
storage/zynq7000-flash/tests/flashdrv.c

- change default sector size for Micron n25q128 to run jffs2,
- add MTD and block device interface for flash driver,
- update tests after changes in flash driver.
More detailed information is provided in commit message.

zynq7000-flash: apply libstorage interface to flashdrv

---

_targets/Makefile.armv7a9-zynq7000
storage/zynq7000-flash/Makefile
storage/zynq7000-flash/zynq7000-flash.c

The flash server for the zynq7000 board uses `libstorage` interface to provide communication with a NOR flash memory driver.
The flash memory provides two interfaces for both block and MTD devices. The server creates appropriate device files within initialization procedure:
- **mtdX** - char device (compliant with MTD interface)
- **mtdblockX** - block device allows to make operations: read, write, sync (the internal caching mechanism is implemented in flash driver).
The initial version of the server allows to create partitions and define rootfs partition via arguments to the program. For each partition the MTD char and block device files are appropriately created with the suffix `pX.` Probably, the partition table will be the next step.
**Example usage**:
`zynq7000-flash -r …

storage/zynq7000: add flash server

---

storage/imx6ull-flashnor/flashnor-ecspi.c
storage/imx6ull-flashnor/flashnor-ecspi.h
storage/imx6ull-flashnor/flashnor.c

Added printing NOR device info (JEDEC ID, chip name and size).
Added missing `const` qualifier for `buff` parameter in `flashnor_ecspiWrite()`
[JIRA: DTR-302](https://jira.phoenix-rtos.com/browse/DTR-302)

imx6ull-flashnor: add driver initialization info

---

storage/imx6ull-flash/flashdrv.c
storage/imx6ull-flash/imx6ull-flashdrv.h

- out-of-bound (oob) size & available size are needed for MTD interface
DTR-102

storage/nandflashdrv: add new fields to flashdrv_info_t

---

storage/imx6ull-flash/Makefile
storage/imx6ull-flash/flashdev.c
storage/imx6ull-flash/imx6ull-flashdev.h

- flashdev intializes storage_dev_t and provides pointers to functions
- flashdev provides interface to NAND flash memory for server as well,
- current version supports only mtd char interface, mtd block is not defined,
- some of the functions derived from the previous mtd implementation from[ phoenix-rtos-filesystems/jffs2/phoenix-rtos/mtd.c](https://github.com/phoenix-rtos/phoenix-rtos-filesystems/blob/master/jffs2/phoenix-rtos/mtd.c)
**Note for reviewers:**
- I am not sure whether function `_flashmtd_errRead` is needed. I leave it to be compatible with previous implementation,
- if bad block occurs, `flashmtd_erase` continues operation - compatibility with flash server implementation. `jffs2` checks bad blocks on its own, so it shoudn't bother it 
- `flashmtd_metaRead` - should …

storage/imx6ull-flash: add mtd interface compatible with libstorage

---

storage/imx6ull-flash/flashdev.c

additional:
- fixing logs
DTR-102

imx6ull-flash/flashdev: remove error checking from _flashmtd_errRead

---

storage/zynq7000-flash/flashdrv.c
storage/zynq7000-flash/zynq7000-flash.c

- flash drv does not longer relies on strg->start which can be different than region's start
- add a parent's storage offset to the partition start
PD-216

zynq7000-flash: add strg->start to flash server in ops invocations

---

multi/stm32l4-multi/tty.c
tty/imx6ull-uart/imx6ull-uart.c
tty/libtty/Makefile
tty/libtty/libtty-lf-fifo.h

16 byte FIFO is added between RX interrupt and tty processing thread.
Without this change TTY driver occasionally looses RX bytes.

stm32l4-multi/tty: add RX fifo buffer written in IRQ

---

_targets/Makefile.armv7a9-zynq7000

JIRA: PP-6
Added _libspi-msg_ to zynq7000 target components
It is impossible to compile applications that use indirect method of spi usage via driver

zynq7000: add recipe for libspi-msg in target Makefile

---

_targets/Makefile.armv7a7-imx6ull
sensors/Makefile
sensors/gps/nmea.c
sensors/gps/nmea.h
sensors/gps/pa6h.c
sensors/include/libsensors.h

- _targets: imx6ull: add sensor manager to default components
- sensors: gps: add implementation for pa6h module
- Client example (specific uart instance with 9600 br should be available in /dev/ directory):
```c
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <libsensors.h>
int main(int argc, char **argv)
{
int fd;
sensors_data_t *data;
unsigned char buff[0x400];
sensor_type_t types;
sensors_ops_t ops = {0};
fd = open("/dev/sensors", O_RDWR);
if (fd < 0) {
return EXIT_FAILURE;
}
/* Get available sensor types */
ioctl(fd, SMIOC_SENSORSAVAIL, &types);
/* Define sensor types request */
ops.types = (types & SENSOR_TYPE_GPS) | (types & SENSOR_TYPE_ACCEL) | (types & SENSOR_TYPE_GYRO) \
| (types & SENSOR_TYPE_GPS);
ioctl(fd, …
```

sensors: add GPS driver to sensor manager

---

gpio/zynq7000-gpio/gpiosrv.c

Fixed missing break.
Simplified `if else` to ternary operator.
[JIRA: PP-46](https://jira.phoenix-rtos.com/browse/PP-46)

zynq7000-gpio: fix missing break in switch statement

---

sensors/baro/lps25xx.c
sensors/imu/lsm9dsxx.c
sensors/libsensors-spi.c
sensors/mag/lsm9dsxx.c
sensors/sensors-spi.h

JIRA: PP-44
- change order of gpiomsg_writeDir() and gpiomsg_writePort()
- changed function name `sensorsspi_initDev()`->`sensorsspi_open`

libsensors-spi: put writeDir() before writePort() + naming change

---

tty/libtty/libtty.c

`libtty` didn't initialize this field causing issues, e.g. here:
https://github.com/phoenix-rtos/phoenix-rtos-devices/blob/802f6d762c11ae58882963526ee682539684f138/tty/zynq7000-uart/zynq7000-uart.c#L395
[JIRA: PP-41](https://jira.phoenix-rtos.com/browse/PP-41)

libtty: add termios c_cflag field initialization in termios_init()

---

tty/uart16550/uart16550.c
tty/uart16550/uart16550.h
tty/uart16550/uarthw-pc.c
tty/uart16550/uarthw-riscv.c
tty/uart16550/uarthw.h

JIRA: RTOS-195 & JIRA-196
- **For JIRA RTOS-195:**
The `uart16550` device driver should create the `/dev/ttyS[0-3]` devices when it detects the presence of a device, but it did not created anything, so it was impossible to communicate with the driver.
I've assigned four serial devices in qemu (` -serial stdio -serial pty -serial pty -serial pty`), the first is on std/io the others are created as `/dev/pts/*` devices which can be nicely used in screen or tmux or to connect with `pppd` + `pppou`.
It was:
With fix
> &nbsp;
> &nbsp;
In sepparate commit the code was refactored to meet changes in coding style (MISRA rules).
- **For JIRA RTOS-196:**
The callbacks `set_baudrate()` and `set_cflags()` were implemented and tested on QEMU and real PC ISA IO card (with 16C550A chip by EXAR, now …

Fixes for uart16550 driver.

---

sensors/imu/lsm9dsxx.c

JIRA: PP-49
Implement and use hardware accelerometer low pass filter. By default cutoff frequency set to 50Hz.

sensors/imu: enable low pass filter on accelerometer readings

---

storage/imxrt-flash/flashdrv.c
storage/imxrt-flash/flashsrv.c
storage/imxrt-flash/imxrt-flashsrv.h
storage/imxrt-flash/tests/flashsrv_raw_tests.c

Fixes the passed pointer to the buffer of directWrite devctl by using a mapped pointer.

imxrt-flash: use mem mapped pointer for directWrite devctl

---

storage/imxrt-flash/flashsrv.c
storage/imxrt-flash/fspi.c

JIRA: RTOS-220
Priority of main thread was set too late.

imxrt-flash: priority set was too late

---

storage/imxrt-flash/flashdrv.c
storage/imxrt-flash/flashsrv.c

Quick fixes for imxrt-flash:
RTOS-224: Synchronize cached writes on close (raw partition)
BES-226: Invalidate sync buffer if it's out of range

imxrt-flash sync improvements

---

sensors/mag/lsm9dsxx.c

JIRA: PP-51
Longer wait is needed for magnetometer thread to not truncate data when sampling the sensor without uisng DRDY (data ready) register check. 
We skip DRDY check as it is not important for us to achieve absolute maximum magnetometer data sampling performance. It comes out, that precise 80Hz sampling causes data loss on some axis. Thus the closest and possibly round value of 64 Hz was chosen as sampling frequency. Tested on zturn drone this fixes the problem.

sensorhub: decrease magnetometer base sampling freq. from 80Hz to 64Hz

---

_targets/Makefile.armv7m7-imxrt106x
usb/ehci/phy-imxrt117x.c

Adds PHY driver for i.MX RT117x targets. To enable particular `OTG`  define e.g. `USB_EHCI_OTG2_ENABLED` in project specific `board_config.h`.
JIRA: NIL-303
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/335

usb: add imxrt117x usb ehci phy driver

---

storage/zynq7000-flash/flashcfg.c
storage/zynq7000-flash/flashcfg.h
storage/zynq7000-flash/flashdrv.c

In current implementation the dual and quad mode does not work correctly for 4 byte addressing mode.
For this reason, the read and page program operations are done on single line.
It should be fixed in the future.
PP-278

storage/zynq-7000: add operations on 4 byte addresses

---

multi/stm32l4-multi/tty.c

This fixes problem introduced in:
2d20738 stm32l4-multi: Support klog
JIRA: ISC-193
Without this fix operations on /dev/uart* fail as device is initialized with invalid port number.

stm32l4-multi: set oid.port when creating uart devices

---

multi/stm32l4-multi/flash.c
multi/stm32l4-multi/flash.h

Add -EINVAL returning in case of unaligment address or size when read from otp.
Fix returning value from otp functions to be signed type.
JIRA: SKAL-527

stm32l4-multi: fix bugs in otp handling

---

sensors/Makefile

JIRA: RTOS-242
Quick fix for:
IMHO libsensors-spi could be a separate component with separate Makefile (or maybe the API should be?).

sensors: fix makefile rule for installing headers

---

adc/ad7779/ad7779-driver.c
adc/ad7779/ad7779.c
dma/imx6ull-sdma/imx6ull-sdma.c

1. Move SPI and GPIO configuration to main init method of ad7779
2. Introduce global timeout for DMA read method

Introduce global timeout to imx6ull-sdma, change ad7779 init procedure

---

tty/imx6ull-uart/imx6ull-uart.c

tty/imx6ull-uart: Fix warning when building with KLOG_ENABLE set to 0

---

tty/uart16550/uart16550.c

uart16550: Fix HW clk not being used in set_baudrate

---

multi/imxrt-multi/uart.c
multi/stm32l4-multi/tty.c
tty/imx6ull-uart/imx6ull-uart.c
tty/libtty/Makefile
tty/libtty/libtty.c
tty/libtty/libtty.h
tty/pc-tty/ttypc_vt.c
tty/spike-tty/spike-tty.c
tty/uart16550/uart16550.c
tty/zynq7000-uart/zynq7000-uart.c

RTOS-259
If the initial baudrate differs from `B115200`, there is no chance to change it using ioctl to `B115200`. 
Invocation of `libtty_init` has been changed in the whole repository.

libtty: add baudrate parameter to initialization function

---

storage/zynq7000-flash/qspi.c

This uninitialized variable caused undefined behaviour for -Og compilation flag.
RTOS-253

zynq7000-flash/qspi: fix uninitialize variable

---

usb/ehci/phy-imxrt117x.c

JIRA: RTOS-268
Fixes: USB PHY on `imxrt117x` does not set platformctl `lpcg.op` field in `setClock()`

Fix: USB PHY on `imxrt117x` does not set platformctl `lpcg.op` field in `setClock()`

---

multi/stm32l4-multi/libmulti/include/libmulti/libaes.h
multi/stm32l4-multi/libmulti/libaes.c

Initialization Vector and key can now be retrieved from the AES peripheral. This makes it possible to perform encryption/decryption on non-contiguous data - IV and key can be stored in a software context for later use.
Decryption key can be generated on-demand instead of forcing the operation every time some buffer is to be decrypted. The key can then be stored in a software context and reused without the need to generate it again.

stm32l4-multi: Extend API with IV and key (derived or not) retrieval

---

multi/stm32l4-multi/flash.c

Added keepidle during operations on flash so as to avoid random delays and possible write failures

stm32l4-multi: Fix unstable writes to internal flash

---

multi/imxrt-multi/gpio.c

imxrt-multi: Use correct union member in gpio_set_dir

---

multi/stm32l4-multi/libmulti/libdma.c
multi/stm32l4-multi/libmulti/libspi.c

SPI peripheral was not deinitialized properly and consistently in all modes of operation (read, write, readwrite, with or without DMA), thus potentially leaving unprocessed data in FIFOs. This change makes the peripheral enabled only for the time of a transaction and deinitializes it afterwards. Also, a few missing data barriers were added for SPI and DMA.

stm32l4-multi: Fix SPI deinitialization procedure

---

adc/ad7779/imxrt/dma.c
adc/ade7913/ade7913-driver.c
dma/imxrt-edma/imxrt-edma.c

EDMA may be used by multiple drivers at the same time so channel number must be checked inside error ISR to make sure it's our error. EDMA initialization is done by first driver calling edma_init().
JIRA: BES-239

edma: add support for multiple EDMA drivers

---

storage/imxrt-flash/flashsrv.c

512 bytes result in stack overflow on BES while erasing sectors (verified by kernel stack canary and gdb watchpoint).
JIRA: BES-240

imxrt-flash: increase stack size for RAW partitions

---

sensors/baro/lps25xx.c
sensors/baro/ms5611.c
sensors/gps/pa6h.c
sensors/imu/lsm9dsxx.c
sensors/mag/lsm9dsxx.c
sensors/sensors.c
sensors/sensors.h

Introduced and used defines for priorities of messaging thread and sensor threads.
Sensorhub works between the low-level bus drivers (e.g spi) which are typically on priority 2 and higher level user applications which are typically on priorty 4. Thus it is sensible to run it on priority level 3.

sensorhub: change default priorities of threads

---

sensors/imu/lsm9dsxx.c
sensors/include/libsensors.h

JIRA: PP-119
Adding delta angle integral values for gyroscope API. That way less data is lost for higher level application if it is performing time integration of gyroscope data.
Gyroscope values are often used for attitude estimation rather that sole angular speed measuring. This includes time integration of gyroscope data to acquire changes in angles. Currently higher level application that wants to fully utilize sensorhub gyroscope data needs to match its polling speed with sensor output data rate. Although this change doesn`t improve performance of angular speed reading it helps for mentioned AHRS algorithms.

sensorhub: add delta angle to gyroscope API

---

gpio/zynq7000-pwm/zynq7000-pwm-msg.c
gpio/zynq7000-pwm/zynq7000-pwm-msg.h

JIRA: PP-119
Adding define in `zynq7000-pwm-msg.h` that specifies the number of channels available in pwm driver.
Although it is redundant to `PWM_NCHAN` in `pwm.c` there is currently no better place to define it so that it is accessible on user level. Without this define the size of 8 channels must be magically defined in user application and thus the driver related values are hardcoded in user application, which is structurally not very nice.

zynq7000pwm: channels number define in api

---

sensors/gps/nmea.c
sensors/gps/nmea.h
sensors/gps/pa6h.c
sensors/include/libsensors.h

1) Addition of velocity error field to gps data structure
2) Remove some of redundancies in parsing/interpreting nmea messages
- nmea parsers do not return message type. They store it inside message structure passed to them
- interpreter does not return message type.
- pa6h_update returns information about the need of publishing new data
- hdop/vdop values are insufficient by itself to calculate error in position in SI units. For this an arbitrary value of base (minimum) error in position/velocity is needed which is device specific. Therefore calculation of such error must be done  in the driver module
- update logic was corrected

pa6h: more error calculations

---

sensors/gps/pa6h.c

JIRA: PP-90
Removing two possible bugs:
1) nul terminating message at the end of `pa6h_receiver` has a bug that nul terminates it one character to far. This can cause the off-by-one error and writing outside of the buffer if message is unfortunately alligned at the end of the buffer.
2) in an unfortunate event of message clipping a situation can occur where nul-terminating previous message causes `$` of the next message to be overwritten with `\0`.
Fixes issue:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/612

pa6h: fix off-by-one during nul-terminating messages

---

sensors/gps/nmea.h
sensors/gps/pa6h.c
sensors/include/libsensors.h

- Using `double` variable type for calculations on latitude and longitude to not loose accuracy.
- Using `int64_t` as transfer data type for longitude and latitude to not loose accuracy
- Transferring latitude and longitude in nanodegrees (10^9 * [deg]). This gives worst case scenario (on equator) accuracy of 100µm/LSB which is far more that necessary.

sensors/gps: increase accuracy of lat/lon with `double`/`int64_t` type

---

tty/pc-tty/ttypc_kbd.c
tty/pc-tty/ttypc_vga.h
tty/pc-tty/ttypc_vt.c
tty/pc-tty/ttypc_vt.h
tty/pc-tty/ttypc_vtf.c

This change is addressed to fix issues with `busybox/vi` and `psh/edit`:
* Fixes https://github.com/phoenix-rtos/phoenix-rtos-devices/issues/102
* Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/487 (requires additional tiny change in `psh/edit` --  https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/173)
This change introduces:
* compatibility with terminals that support bright colors (VGA), for foreground`ESC [ 90 m` `ESC [ 97 m`, and background `ESC [ 100 m` - `ESC [ 107m`.
* compatibility with terminals that support independent reset of only colors using: `ESC [ 39 m`  (reset foreground color), `ESC [ 49 m` (reset background color), to reset all attributes and colors using: `ESC [ 0 m`
* adds emulation of `bold` attribute by using brighter color (when used with …

pc-tty: CSI extensions and fixes for `busybox/vi`, `psh/edit`

---

storage/imx6ull-flash/flashsrv.c
storage/zynq7000-flash/zynq7000-flash.c

JIRA: DTR-389
Fix storage size checks
Errorneus checks made it impossible to erase last sector or write to last byte.

storage: fix storage size checks

---

storage/host-flash/Makefile
storage/host-flash/host-flash.c
storage/host-flash/host-flash.h
storage/host-flash/host-flashsrv.c

host-flash: add powerctrl
Adding powerctrl to host server allows to test correctness of thos meterfs feature.
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/353

host-flash: add powerctrl

---

spi/imx6ull-qspi/qspi.c

On error `mmap()` returns `MAP_FAILED` not `NULL`

qspi.c: fix incorrect condition on return error by mmap()

---

sensors/simsensor_common/simsensor_reader.c
sensors/simsensor_common/simsensor_reader.h

Now reader doesn't use `int` for sensor type, but secial `sensor_type_t`
More elegant code.

simsensor reader: fix type of sensor types

---

sensors/gps/common.c

Fixing error where sizeof of char pointer was used instead of the variable that holds the buffer size.
This error is legacy error, previousely this buffer was static and sizeof usage was correct.
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/370#issuecomment-1551874641

sensors: use `rcv->bufSz` in gps common

---

sensors/gps/common.c
sensors/gps/nmea.c
sensors/gps/nmea.h
sensors/gps/ubx.c
sensors/include/libsensors.h

- adding utc field to gps messages indicating real fix time of messages
- read-sleeping in common gps code

sensors: `utc` field and `read()`-sleeping in gps

---

sensors/Makefile

JIRA: PP-153
Adding option to select what sensors are compiled via `DEVICE_SENSORS` environment variable.
As mentioned in https://github.com/phoenix-rtos/phoenix-rtos-project/issues/744 sensors have no selection on what drivers are compiled (i.e. everything is compiled).
This somehow patches (not solves!) the issue of compiling zynq7000-dependent code on non-zynq7000 targets as lack of `DEVICE_SENSORS` in `_projects/<non-zynq-target>/build.project` won`t activate a compilation of such sensors. However this solution should be treated as complementary to future changes in devices/sensors that will add more generic api for those instances of sensors which use target-dependent code.

sensors: compile-time sensors selection

---

storage/zynq7000-flash/flashdrv.c
storage/zynq7000-flash/qspi.c

JIRA: RTOS-481
Changed timeouts to prevent timeouts on starvation.
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/725

zynq7000-flash: timeouts rework

---

adc/ade7913/ade7913-driver.c

Change the way the interrupt counter is read from the ADC driver. The counter value will now be copied (msgSend <-> msgResponse) instead of sharing a direct pointer to a memory location between processes. A change in the procedure of reading samples in the metering server is required: block on msgSend until the driver interrupt handler signals the condWait to the sample read process.
JIRA: NIL-433

ade7913: Change read of interrupt counter

---

tty/pc-tty/ttypc_vt.c

By default `libtty` sets `TAB3` a.k.a. `XTABS` oflag so internally all `TAB` (\x09) characters are expanded to series of spaces (\x20). The `pc-tty` understands `\x09` character and `TABSTOP` setting, but `TAB expansion`, `enabled by default` in `libtty` distorts the way `pc-tty` displays `TABs`, resulting `in misaligned columns`. Disabling XTABS after `libtty_init()` solves the problem of `pc-tty` not displaying TABS correctly.
JIRA: RTOS-518
Before:
After (with this patch):
Result of:
`printf("%ld\t%s\n", size, path);`

pc-tty: Disable libtty TAB expansion

---

sensors/mag/lis2mdl.c

Inverting Y axis of lis2mdl measurement so that final measurement is in right-hand correct frame of reference.
Lis2mdl, by default, does not return data in frame of reference that follows the right-hand rule. Inverting its Y axis fixes the problem. Below is the screenshot of lis2mdl datasheet Rev 5, section 1.2 which presents the default axis directions:
Current code followed the lsm9ds1 magnetometer driver code which **did** follow the right hand rule, thus the fix needed.

sensors: lis2mdl right-handness fix

---

multi/imxrt-multi/cm4.c

- allow custom RX/TX FIFO size through "board_config.h"
- read status register in IRQ handler only once
JIRA: NIL-291

imxrt117x: CM4 MU optimizations

---

adc/ade7913/adc-api-ade7913.h
adc/ade7913/ade7913-driver.c

After [separating the `API` of `ADE7913` and `AD7779`](https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/351), there is no need to maintain a common API anymore, especially since `ADE7913` does not require channel calibration (in chip) or channel selection (API may be simpler), each ADE7913 device has three channels (I0, V1, V2) by default (no option to disable particular channels). The application receives a stream of data from which it is able to read the device status, CRC along with samples.
JIRA: NIL-452
API readability.

ade7913: remove unused part of API

---

adc/ade7913/ade7913-driver.c

The ade7913 driver is run from RAM (dtcm), strerror messages are not needed to decode the reported error, it is more important to save memory.
JIRA: NIL-452

ade7913: remove strerror to reduce memory footprint

---

storage/zynq7000-flash/flashcfg.c
storage/zynq7000-flash/flashcfg.h
storage/zynq7000-flash/flashdrv.c
storage/zynq7000-flash/qspi.c
storage/zynq7000-flash/qspi.h

Initialize configuration registers on flash memories so that we send proper amount of dummy cycles for the frequency we operate at.
Add workaournd to bug in zynq hardware.
Rewrite qspi_polledTransfer to improve readability.
Switch to faster command for page program and read.

zynq7000-flash: initialize configuration registers

---

multi/imxrt-multi/imxrt-multi.c

* Add default handler in case of unhandled device. The lack of a handler for gpio 10-13 resulted in an incorrect error return value.
* Fix unhandled GPIO no. 10-13 on i.MX RT117x target
JIRA: RTOS-601

imxrt-multi: fix unhandled gpio 10-13 on rt117x

---

multi/stm32l4-multi/common.h
multi/stm32l4-multi/config.h
multi/stm32l4-multi/fs.c
multi/stm32l4-multi/i2c.c
multi/stm32l4-multi/spi.c
multi/stm32l4-multi/stm32l4-multi.c
multi/stm32l4-multi/tty.c
multi/stm32l4-multi/uart.c

Peripherial defaults removed from config.h - project shallset required peripheria explicitly in board_config.h.
Added error when UART_CONSOLE is not set and warning on console setted to disabled UART. Moved errors to .c file to not reporting it many times.
Reduce config.h variable propagation by removing unnecessary includes and move computed variables to valid .c file.
JIRA: DEND-32
Better control of enabled/disabled peripheria via board_config
Small clean up.
Need to define missing variables in case that project rely on that

stm32l4-multi: Reorganize config, disable defaults

---

multi/stm32l4-multi/config.h
multi/stm32l4-multi/libmulti/include/libmulti/libdma.h
multi/stm32l4-multi/libmulti/include/libmulti/libspi.h
multi/stm32l4-multi/libmulti/libdma.c
multi/stm32l4-multi/libmulti/libspi.c
multi/stm32l4-multi/tty.c
tty/libtty/fifo.h
tty/libtty/libtty-lf-fifo.h
tty/libtty/libtty.c
tty/libtty/libtty.h
tty/libtty/libtty_disc.c
tty/libtty/libtty_disc.h
tty/libtty/ttydefaults.h

JIRA: DEND-42
Add option to handle tty using DMA. Enablind DMA and buffer sizes are configurable.
UART interface will be done in separate PR.
Tested by sending 2048 characters at once.
Handling using interrupts was too slow and resulted in dropping characters.

stm32: add option to handle tty using DMA

---

multi/imxrt-multi/config.h
multi/imxrt-multi/fs.c
multi/imxrt-multi/imxrt-multi.c
multi/imxrt-multi/uart.c

Allows you to change the priority of `imxrt-multi` (all threads) at once - as desired by the project (board_config using `IMXRT_MULTI_PRIO`). If `libdummyfs` is linked to `imxrt-multi`, it will use its priority (imxrt-multi), this fixes race problem with `imxrt-flash` on write to flash, when `libdummyfs` is used.
JIRA: NIL-459

imxrt-multi: make fs & uart priority settable also

---

multi/stm32l4-multi/config.h
multi/stm32l4-multi/tty.c
tty/libtty/libtty-lf-fifo.h

https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/426

stm32l4: drop oldest bytes in case of overrun

---

tty/imx6ull-uart/imx6ull-uart.c

imx6ull-tty: Init libklog on console only

---

storage/imxrt-flash/fspi.c

Change replaces busy waits with calls to reschedule (yield) using `usleep(0)`. Applies optimizations to opRead/opWrite, and adds millisecond timer which handles timed out operations.
JIRA: RTOS-678

imxrt-flash: optimize opRead/opWrite add cpu yield

---

_targets/Makefile.armv7a9-zynq7000
libmbr/Makefile
libmbr/libmbr.h
storage/zynq7000-sdcard/Makefile
storage/zynq7000-sdcard/sdcard.c
storage/zynq7000-sdcard/sdcard.h
storage/zynq7000-sdcard/sdhost_defs.h
storage/zynq7000-sdcard/sdstorage_dev.c
storage/zynq7000-sdcard/sdstorage_dev.h
storage/zynq7000-sdcard/sdstorage_srv.c
storage/zynq7000-sdcard/zynq7000-sdio.c
storage/zynq7000-sdcard/zynq7000-sdio.h

Adds a storage driver for SD memory cards. Data can be read through a block device or a JFFS2 partition can be mounted through an emulated MTD character device.
The driver uses the SD Host Controller built into the Zynq 7000 platform to communicate with the SD card. Accesses to the card (for both block and MTD device files) are passed through `libcache`. Partitions are dectected automatically upon card insertion using MBR partition scheme (typical on SD cards). Separate device files are created for each partition. Card removal results in partitions being unmounted and device files being removed. No "safe eject" functionality has been implemented yet.
The MTD device is described as "emulated" as there is no way to implement a fully featured MTD driver for an SD card. Driver supports JFFS2 …

zynq7000: add SD card storage driver

---

storage/zynq7000-flash/qspi.c
storage/zynq7000-sdcard/sdcard.c
storage/zynq7000-sdcard/sdstorage_dev.c

Fix for SD card driver to work on QEMU, small improvement in NOR flash driver performance, 
* SD card: SD host controller on QEMU works a bit differently from the one on physical hardware and needed a small adjustment.
* SD card: Set emulated MTD device minimum write size to 1 so that existing rootfs images can be mounted.
* NOR flash: Small improvement in QSPI transfer performance by locking mutex once per function call instead of once per loop iteration.
SD card driver is useful under QEMU because it is much faster than the emulated NOR flash driver. It may be desirable to mount rootfs from the emulated SD card.

zynq7000: fixes and improvements for QEMU

---

multi/stm32l4-multi/libmulti/include/libmulti/libuart.h
multi/stm32l4-multi/libmulti/libuart.c

This change improves IRQ uart performance. Changing inter octet timeout to absolute timeout allows passing bigger read buffers without risk of long block.
Currently IRQ uart does not work reliably on _redacted_ project that uses STM32 with limited CPU clock. Problems seem to appear mostly when both TX and RX are used. With this changes 9600 seems to be working without issues.
- [x ] Breaking change (fix or feature that would cause existing functionality to change)

improve stm32l4 IRQ uart driver

---

storage/imxrt-flash/flashdrv.c
storage/imxrt-flash/flashdrv.h
storage/imxrt-flash/flashsrv.c
storage/imxrt-flash/imxrt-flashsrv.h

The change implements reading from the window of write buffer while the source area is overlapping with window of write buffer space. The goal of this implementation is to make reads consistent with the buffered write mechanism through posix API (open, read/write, close) and to force write of pending buffer data using sync.
The change adjusts the naming of functions used internally (directRead/Write vs bufferedRead/Write)
API changes: direct reading of raw partition is moved to devctl. Using posix (read/write) it is possible to use buffered reads and writes only.
JIRA: NIL-479

imxrt-flash: implement read from window buffer

---

storage/imxrt-flash/flashsrv.c
storage/imxrt-flash/imxrt-flashsrv.h

Allows to perform direct operations (read/write/sector erase) on specific device/partition from user code.
JIRA:NIL-471
as above
Overriding custom init function and utilizing internal flashsrv functions creates a safe way for operating on partitions with sensitive data (e.g. program code). Message interface for such partition can be stripped of write/read/erase functions to increase safety.

imxrt-flash: add custom flashsrv init option

---

multi/imxrt-multi/Makefile
multi/imxrt-multi/imxrt-multi.c
multi/imxrt-multi/posixsrv.c

Add optional support for `libposixsrv` on i.MX (`rt1176`, `rt1064`), but use `libpseudodev` on `rt1052`, because of low RAM footprint.
`libpseudeodev` and `libposixsrv` may conflict and shall be used exclusively.
In [board_config.h](https://github.com/phoenix-rtos/phoenix-rtos-project/blob/master/_projects/armv7m7-imxrt117x-evk/board_config.h#L20) comment out `#define PSEUDODEV 1` and add `#define BUILTIN_POSIXSRV 1`
memory usage (builtin posixsrv, without libpseudodev):
memory usage (builtin pseudodev, without libposixsrv)
memory map:
```
0 itcm   262144 bytes
1 dtcm   163840 bytes
2 ocram2 524288 bytes
3 xip1   4194304 bytes
```
mostly ptys, pipes
JIRA: RTOS-641
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/176
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/984

imxrt-multi: add support for optional libposixsrv

---

adc/ade7913/adc-api-ade7913.h
adc/ade7913/ade7913-driver.c
adc/ade7913/flexpwm.c
adc/ade7913/flexpwm.h

Changes introduced:
1. Moves DREADY config to board config
2. Adds possibility to setup all FlexPWMs (1-4) each of its submodules (0-3) and input pins A, B, X. In total 48 inputs.
3. Adds the functionality of turning on and off the power supply of ADCs for newer revisions of PCB.
JIRA: NIL-456

ade7913: add on/off power supply control, extend flexpwm

---

multi/stm32l4-multi/Makefile
multi/stm32l4-multi/config.h
multi/stm32l4-multi/posixsrv.c
multi/stm32l4-multi/stm32l4-multi.c

This change adds `libposixsrv` to stm32l4-multi (`stm32l4-nucleo` target). The use of `libposixsrv` is optional and can be enabled by defining `BUILTIN_POSIXSRV` in `boardconfig.h` per project.
Requires update in phoenix-rtos-build 
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/179
and in phoenix-rtos-project
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1019
JIRA: RTOS-641
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/179

stm32l4-multi: add support for optional libposixsrv

---

multi/imxrt-multi/spi.c

DONE: RTOS-755
`spi_transaction` msg may return (read) less bytes than requested (e.g. 8 out of 10). RX FIFO watermark is set to 0 on `spi_config` msg and never changed, meaning that _Receive Data_ event is asserted after putting one word into FIFO. This change sets the RX watermark to an appropriate value so that data is read after it is fully received.

imxrt-multi/spi: Fix RX FIFO being read too early

---

usb/ehci/ehci-hub.c

EHCI root hub currently returns incorrect data (and incorrect amount of data) when queried for the configuration descriptor. This PR fixes the problem.
Currently the code [parsing configuration descriptors](https://github.com/phoenix-rtos/phoenix-rtos-usb/blob/7358b3f44e0bbb66606381618f49437fd5f3cc75/usb/dev.c#L238) in phoenix-rtos-usb requires a special case for the root hub because the descriptor cannot be parsed otherwise.

usb/ehci: fix root hub descriptors

---

_targets/Makefile.sparcv8leon3-gr716
dma/grdmac2/Makefile
dma/grdmac2/grdmac2.c
dma/grdmac2/grdmac2.h
multi/grlib-multi/Makefile
multi/grlib-multi/adc.c
multi/grlib-multi/gpio.c
multi/grlib-multi/grlib-multi.c
multi/grlib-multi/spacewire.c
multi/grlib-multi/spi.c
multi/grlib-multi/uart.c
tty/grlib-uart/grlib-uart.c

sparcv8leon3: add DMA support to uart driver

---

multi/imxrt-multi/config.h
multi/imxrt-multi/uart.c

The rx overrun flag is cleared in the interrupt handler. The hardware fifo turns out to be too small (four octets) and cannot be increased (read only register on imxrt1176). RX bytes were lost in irq handler. To solve the issue this change adds small FIFO between the interrupt and the thread to improve performance significantly. "Lock-free FIFO" from libtty implementation used to accomplish this.
Additionally, statistics regarding the counting of (software and hardware) overrun events are introduced.
Removed unused variable in uart_common, and corrected clock settings for imxrt1176 to behave like on imxrt10xx (just make clock run).
This change allows to set libtty buffers for each uart instance separately. By default, the UART_BUFSIZE setting for an instance will be overridden by the …

imxrt-multi/uart: add intermediate rx fifo between irq handler and thread

---

multi/stm32l4-multi/libmulti/libuart.c

stm32l4-multi/uart: Set txend before setting txbeg for safety

---

tty/uart16550/uart16550.c

On RV64 systems interrupt handler is remapped before executing interrupt. On mulicore system, without this change, the remap influences all cores, which may be executing nearby code, causing page fault.
JIRA: RTOS-813

uart16550: place irq handler in .interrupt section on riscv64

---

multi/imxrt-multi/spi.c

These changes prevent unwanted gpio initialization in the absence of spi settings and fix initialization swap for spi5 and spi6.
This solves the problem of reconfiguring mux gpio for pctl_mux_gpio_emc_b1_00 in case of lack initialization settings for all spi pins for IMXRT117X. pctl_mux_gpio_emc_b1_00 is seen in the code as 0 which corresponds to no spi initialization. gpio mux pctl_mux_gpio_emc_b1_00 is not valid for any spi interface. Any invalid mux for spi is marked with a forbidden value of mux to prevent unwanted initialization. This change is required in case of use gpio_emc_b1_00 as simple gpio for example.
Next solved problem is swap mux value for spi5 and spi6.

imxrt-multi: fix bug in spi initialization

---

storage/imxrt-flash/flashsrv.c
storage/imxrt-flash/imxrt-flashsrv.h

CRC32 can be calulated for selected region of flash memory or raw partition. To calculate automatically CRC32 of whole memory/partition set addr and len to 0.
JIRA: NIL-574

imxrt-flash: support for calulating CRC32 of selected region

---

storage/imxrt-flash/fspi.h

Adds enums common to the plo implementation, so that it can be used in per project `board_config.h` instead of using magic numbers.
e.g.:
`#define FLEXSPI2_PORT_MASK (flexspi_slBusA1 | flexspi_slBusA2 | flexspi_slBusB2)`
instead of magic numbers:
`#define FLEXSPI2_PORT_MASK (1 | 2 | 8)`
JIRA: NIL-539

imxrt-flash: add port and bus mask enums

---

storage/imxrt-flash/flashsrv.c

Meterfs stack size needs to be increased as it overflows (happened when flash was empty and files were to be created)
Add exclusive access for single PID. According to POSIX behavior of O_EXCL mode of open (when O_CREAT is unset) is undefined. This change interprets O_EXCL flag as exclusive access for a process that performs `open` on partition until `close`.
Adding exclusive access to partition is an easy, probably temporary solution to restrict access to sensitive memory spaces

imxrt-flash: allow exclusive access to raw partitions 

---

tty/zynq7000-uart/zynq7000-uart.c

Here is how the race condition could happen:
This race happens because of the assumption that if the IRQ is active, then the IRQ is already disabled. However, in the case above it is not disabled yet and will be disabled a bit later - and never re-enabled, because IRQ was cleared.
This race could not happen in single-core configuration because in ISR checking the IRQ active register and disabling IRQ could never be interrupted (and was effectively atomic). However, when SMP is enabled the thread and ISR can be scheduled on different cores and can interleave in the way described.
After the change the IRQ mask register is checked. In this handler code, the only way RX threshold IRQ can be disabled is if the IRQ is active and the ISR has completed. Updating the mask register is atomic and no …

zynq7000-uart: fix race condition

---

_targets/Makefile.riscv64-noelv
dma/grdmac2/grdmac2.c
multi/grlib-multi/grlib-multi.h
tty/grlib-uart/grlib-uart.c
tty/spike-tty/spike-tty.c

add support for `riscv64-noelv` target

---

multi/imxrt-multi/Makefile
multi/imxrt-multi/config.h
multi/imxrt-multi/i2c.c
multi/imxrt-multi/i2c.h
multi/imxrt-multi/imxrt-multi.c
multi/imxrt-multi/imxrt-multi.h
multi/imxrt-multi/imxrt1170.h
multi/imxrt-multi/trace.h

imxrt-multi: Implement i2c driver

---

multi/imxrt-multi/Makefile
multi/imxrt-multi/config.h
multi/imxrt-multi/i2c.c
multi/imxrt-multi/i2c.h
multi/imxrt-multi/imxrt-multi.c
multi/imxrt-multi/imxrt-multi.h
multi/imxrt-multi/pct2075.c
multi/imxrt-multi/pct2075.h

Added driver for PCT2075 temperature sensor to imxrt-multi.
Implementation is the same as NCT75 driver already in the repo, but is integrated with the multidriver.
Configuration (bus number and device address) can be defined at compile time through `board_config.h`.
JIRA: NIL-586

imxrt-multi: add PCT2075 I2C temperature sensor

---

adc/ade7913/ade7913-driver.c
adc/ade7913/ade7913.c
dma/imxrt-edma/imxrt-edma.c

- fix support for 3x ADE invocation
- fix EDMA per-channel functions
NIL v33

ade7913 driver improvements

---

storage/pc-ata/ata.c

Some hardware (tested on ThinkPad E540) use uncommon ATA IO port addresses instead of typical 0x1f0, 0x3f6, 0x1e8, 0x3ee. In such case, these addresses are often located in pci BAR0-BAR3 of the storage device. This change utilizes BARs via platformctl/pctl_get if nothing is found on common addresses
JIRA: RTOS-922

pc-ata: set IO port addresses based on pci BARs

---

storage/imxrt-flash/flashsrv.c

Detect active "bank" (the partition from which the flashsrv was loaded) and create symlink `/dev/root` to that partition.
JIRA: NIL-644

imxrt-flash: add optional "bank" detection on startup

---

multi/imxrt-multi/cm4.c

Useful when we need to run new code on an already running M4 core. The error code EALREADY allows us to detect this situation, in which case the new code should be started by resetting the M4 core.
DONE: NIL-441

imxrt-multi: CM4_RUN_CORE returns EALREADY if core is running

---

storage/imxrt-flash/flashsrv.c

Added a flash mutex lock during meterfs_init as it may involve sector erasure.
DONE: NIL-584

storage/imxrt-flash: meterfs: lock mutex during meterfs_init

---

multi/grlib-multi/uart.c

JIRA: RTOS-883
Initialize UART clock if necessary on the GR740.
This worked previously because the clock is already inintialized in kernel, but would be necessary in case of different UART use.

grlib-multi: initialize CGU on GR740

---

tty/pc-tty/event_queue.c
tty/pc-tty/event_queue.h
tty/pc-tty/ttypc.h
tty/pc-tty/ttypc_kbd.c
tty/pc-tty/ttypc_mouse.c
tty/pc-tty/ttypc_mouse.h
tty/pc-tty/ttypc_ps2.c
tty/pc-tty/ttypc_ps2.h

JIRA: RTOS-896, RTOS-864
Adds PS/2 mouse support. Because PS/2 keyboard and mouse share the same I/O port, this required some heavy refactoring of ttypc_kbd driver. It also adds `/dev/kbd` and `/dev/mouse` virtual devices, which can be used for input event capturing by applications, for instance by an X server, as part of RTOS-864.
Mouse support and virtual devices are opt-in and can be enabled via `board_config.h`.
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1135

pc-tty: add PS/2 mouse support and kbd/mouse vdevs

---

multi/grlib-multi/Makefile
multi/grlib-multi/spacewire.c
multi/imxrt-multi/Makefile
multi/stm32l1-multi/Makefile
multi/stm32l4-multi/Makefile
sensors/libsensors-spi.c
storage/zynq7000-flash/qspi.c
tty/zynq7000-uart/zynq7000-uart.c

JIRA: RTOS-927
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1006
Refactor to prevent new GCC warning.
Disable array-bounds checks in multi as fixing it would require a lot of work.

misc: adapt to gcc 14.2

---

gpio/zynq7000-pwm/zynq7000-pwm-msg.c

PP-263
Added oid assignment to message structure before sending it.
pwm driver worked improperly without assigning oids to messages.

gpio: add oid assignment to message in zynq7000 pwm driver

---

multi/imxrt-multi/uart.c
tty/zynq-uart/zynq-uart.c

`ioctl(KIOEN)` should be handled by console device drivers, not passed to libtty. With some drivers it already happens, with some it doesn't, leading to `libtty: unsupported ioctl` warning
JIRA: RTOS-1034

Fix ioctl(KIOEN) not being handled by all tty device drivers

---

can/zynqmp-can/zynqmp-can.c

Add an option to route CAN peripheral RX/TX pins via programmable logic subsystem
Tested on autopilot board, it works well
JIRA: PP-271

zynqmp: add option to route CAN via PL

---

storage/umass/umass.c
tty/usbacm/usbacm.c

https://github.com/phoenix-rtos/phoenix-rtos-usb/pull/36

usb: Adapt drivers to events API

---

multi/imxrt-multi/config.h
multi/imxrt-multi/imxrt-multi.c

imxrt-multi: Fix -Wundef warnings with a few macros

---

tty/usbacm/usbacm.c

First commit fixes mem exception on DTR caused by use-after-free for any nodes with id higher than 0 due to wrong error handling in `_usbacm_devAlloc`

usbacm: idtree bug fixes

---

_targets/Makefile.armv7r5f-tda4vm
tty/uart16550/Makefile
tty/uart16550/uart16550.c
tty/uart16550/uart16550.h
tty/uart16550/uarthw-tda4vm.c

Added hardware abstraction files for TDA4VM target.
To make the `uart16550` driver compatible with the UART on TDA4VM some changes had to be made concerning interrupt handling. On that platform the UART interrupt is level-triggered and cannot be reconfigured to be edge-triggered. Additionally, trying to mask the data ready interrupt in the `IMR` register has no effect after the interrupt has been asserted. To solve this, the hardware FIFO is read into a buffer until the data ready interrupt flag is down.
Code has been tested on `ia32-generic-qemu` and `riscv64-generic-qemu` and found to work. It also achieves better performance because it reads FIFO fully before re-enabling the interrupt (thus avoiding interrupt handling overhead).

tty/uart16550: add TDA4VM target

---

sensors/Makefile
sensors/imu/mpu6000.c
sensors/locsensor.c
sensors/server-include/libsensors/local/sensors.h
sensors/server-include/libsensors/sensor.h

This PR changes (incrementally) sensors registration API. Now it is possible to use sensors libraries both in sensorhub (as a separate sensor data server) and in local binaries (as locally allocated sensors). Though it is not possible to use them both at the same time.
`libsensors/local/sensor.h` serves an API for standalone application to use sensors. Sensor registration process is still auto-magic through constructors. The `locsensor` user should redirect its own `sensor_register()` and `sensor_publish()` to the locsensor functions. `locsensor_publish()` is stub-implemented (there is no possibility now for establishing local thread with server. 
An entry implementation was done with `mpu6000` sensor. Additional commits that restructure each sensor has to follow.

sensors: add local sensors API
